### ISSUE TITLE
Referências de artigos em XML perdem a acentuação em "Como citar este artigo".

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/Web#100]
Por gentileza, verificar porque as referências de artigos em XML perdem a acentuação. 
Verifiquei que os artigos em HTML do CSP não apresentam esse problema nas referências em "Como citar este artigo".

**Comment by robertatakenaka** [comment]
@francine-curivil : Por favor, localizar os fascículos em que isso acontece e colocar os pacotes de XML no FTP novamente.

**Comment by francine-curivil** [comment]
Roberta,

O Abel havia verificado que isso estava acontecendo com os fascículos da BN
e me informou. Quando eu olhei e te falei estava faltando a acentuação,
todavia olhei novamente e está certo. Dessa forma esse ticket pode ser
concluído.

Att.,
--
Francine Curivil
Bibliotecária
SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - Fap UNIFESP
______________________________
Av. Onze de Junho, 269
Vila Clementino – São Paulo – SP – Brasil
CEP. 04041-050
Telefone: (55 11) 5083-3639 - R. 111
www.scielo.org | www.scielo.br

2015-03-23 17:23 GMT-03:00 Roberta Takenaka <notifications@github.com>:
