### ISSUE TITLE
Codificação em Título de Sumário (site e homolog)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/Web#154]
Quando é necessário inserir algum caracter especial nos títulos dos artigos, os sumários eletrônicos tanto do homolog quando do site scielo.br não conseguem interpretar o código e deixaa informação como um ponto de interrogação.

Exemplo real: bjmbr ahead lote 1814 artigo: 1414-431X-bjmbr-1414-431X20142765
Caminho no V: V:\SciELO\serial\bjmbr\2014nahead\1414-431X-bjmbr-nahead1814

![pdf_bjmbr_lote1814](https://cloud.githubusercontent.com/assets/6084959/3130950/e9ae2440-e7fe-11e3-8898-cdf488d43611.jpg)

Este "B" que representa "beta minúsculo" na imagem do pdf não aparece nos sumários, tanto do homolog:
Ver em: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0100-879X20140050&lng=en&nrm=iso

E nem no sumário do site.
Ver em: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0100-879X20140050&lng=en&nrm=iso

No link do texto a informação fica OK.

**Comment by robertatakenaka** [comment]
@RPostalli : por favor, reprocessar o fascículo: 
http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=0100-879X20140007&lng=en&nrm=iso a fim de corrigir os problemas de caracteres.

**Comment by robertatakenaka** [comment]
Resolvido
