### ISSUE TITLE
Corrigir a apresentação do resumo e palavras chaves

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/Web#195]
a revista mael apresenta no homolog.xml os títulos dos resumos sempre como "ABSTRACT" sendo que a marcação do XML esta correta, onde não é mencionado no primeiro resumo o atributo xml:lang que deveria herdar da tag article principal. Além disso não está apresentando as palavras-chave do resumo em portugues.

exemplo no homolog: 
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1983-68212014000200007&lng=en&nrm=iso&tlng=pt

Regra no SPS
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#abstract

**Comment by javani** [comment]
Corrigir também no ambiente de homologação já que cria a impressão de erro na marcação. Corrigir em homolog.xml e homolog. 
Exemplo: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0103-507X2014000400339&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@javani: este é outro caso. preciso verificar.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-01-16 11:56 GMT-02:00 javani <notifications@github.com>:
