### ISSUE TITLE
Apresentação de <product/>

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/Web#202]
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1981-77462015000100217&lng=pt&nrm=iso&tlng=pt

no XML tem tudo isso aqui:
```xml
<product product-type="book">
<person-group person-group-type="author">
<name>
<surname>Arruda</surname>
<given-names>Maria da Conceição Calmon</given-names>
</name>
</person-group>
<source>Democratização ou cerceamento? Um estudo sobre a reforma do ensino médio técnico dos anos 1990</source>
<year>2013</year>
<publisher-name>Interciência</publisher-name>
<publisher-loc>Rio de Janeiro</publisher-loc>
<size units="pages">170</size>
<isbn>8571933537</isbn>
</product>
```

Ensaios de sociologia do mercado de trabalho
brasileiro. Adalberto Cardoso. (2013). Rio de
Janeiro: FGV, 2013, 264p.

**Comment by leticiaquino** [comment]
@robertatakenaka  os possíveis valores para ```<product>```são:

article 	referência de artigo
book 	referência de livro
chapter 	referência de capítulo de livro
other 	outros tipos
software 	referência de software
