### ISSUE TITLE
Apresentação HTML - role

### ISSUE THREAD

**Issue by javani** [scieloorg/Web#222]
Quando o papel do autor é marcado no XML aparece na sequência no site, conforme segue:

Maria Cecília de Souza Minayo, Romeu Gomes, Editors-in-Chief

Quando deveria ser:

Maria Cecília de Souza Minayo, Romeu Gomes
Editors-in-Chief

A estrutura no XML está:

```<contrib contrib-type="author">
<name>
<surname>Gomes</surname>
<given-names>Romeu</given-names>
</name>
<role>Editors-in-Chief</role>
</contrib>
</contrib-group>```

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1413-81232015000100005&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@javani, @leticia: ajustei a XSL, mas funcionará para a seguinte estrutura:

```xml
<contrib-group>

<contrib contrib-type="author"> 
  <name><surname>Minayo</surname> <given-names>Maria Cecília de Souza</given-names></name> 
</contrib> 
<contrib contrib-type="author"> 
  <name><surname>Gomes</surname> <given-names>Romeu</given-names></name> 
</contrib> 
<role>Editors-in-Chief</role> 
</contrib-group>
```

Para que fique claro que o role é para todos os autores e não apenas para o último autor.
