### ISSUE TITLE
Página Beta - Imagens em formato diferente de .jpg não aparecem no artigo

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/Web#227]
Verificamos que para artigos que apresentam qualquer formato diferente de .jpg o programa insere essa extensão a mais, por exemplo:

a imagem de nome 1982-0216-rcefac-16-06-01751-gt2.**png** é apresentada da seguinte forma na página beta:

1982-0216-rcefac-16-06-01751-gt2.**png.jpg**

Ver:
http://www.scielo.br/article_plus.php?pid=S1516-18462014000601751&tlng=pt&lng=pt

Verificar a possibilidade de considerar a extensão já existente.

**Comment by robertatakenaka** [comment]
xsl já estava corrigida mas não foi atualizada nos sites.
