### ISSUE TITLE
Corrigir Licença Creative Commons

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/Web#229]
A mensagem referente à licença Creative Commons (no rodapé das páginas) deve ser corrigida de forma a alinhar-se aos Novos Critérios SciELO (Setembro/2014).

O texto da mensagem deve ser mantido como está, entretanto, a imagem e o link da Licença devem ser referentes à licença CC-BY (http://creativecommons.org/licenses/by/4.0/).

**Comment by robertatakenaka** [comment]
é caso de configuração. Abrirei um chamado para Infra.

@alexxxmendonca: por favor, feche o ticket após confirmar que a infra
atendeu o chamado.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-03-06 9:55 GMT-03:00 alexxxmendonca <notifications@github.com>:

**Comment by alexxxmendonca** [comment]
Deu certo, obrigado!

**Comment by alexxxmendonca** [comment]
Caros,

No site voltou a aparecer a imagem e link BY-NC. O correto é imagem e link da licença CC-BY (ver chamado original).

**Comment by alexxxmendonca** [comment]
Testado e aprovado em produção. Obrigado.
