### ISSUE TITLE
Problema de apresentação de referências com ext-link

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/Web#246]
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-52732015000200175&lng=en&nrm=iso&tlng=en

24.Pedraza DF, Queiroz D. Micronutrientes no crescimento e desenvolvimento infantil. Rev Bras Cres Desenv Hum. 2011; 21(1):155-70. [ Links ]

[ Links ]

[ Links ]

27.Romanelli G. O significado da alimentação na família: uma visão antropológica. Medicina. 2006; 39(3):333-9. [ Links ]

**Comment by robertatakenaka** [comment]
@RPostalli: Parece que o problema é no XML mesmo. O link que está no mixed-citation está diferente do que está no element-citation.

**Comment by RPostalli** [comment]
Roberta esta igual veja

<ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.1136/bmj.39147.604896.55">http://dx.doi.org/10.1136/bmj.39147.604896.55 </ext-link>

<mixed-citation>15.Cook NR, Cutler JA, Obarzanek E, Buring JE, Rexrode KM, Kumanyika SK, et al. Long term effects of dietary sodium reduction on cardiovascular disease outcomes: Observational follow-up of the Trials of Hypertension Prevention (TOHP). BMJ. 2007; 334(7599):885-8. http://dx.doi.org/10.1 136/bmj.39147.604896.55</mixed-citation>

Mas mesmo que estivesse diferente, este problema de link não deveria suprimir todas as informações da ref no site. Não faz sentido.

**Comment by robertatakenaka** [comment]
@RPostalli : não está. Veja:

http://dx.doi.org/10.1136/bmj.39147.604896.55
http://dx.doi.org/10.1 136/bmj.39147.604896.55

Há um espaço indesejável entre os 1 1.
10.1 136/bmj

**Comment by RPostalli** [comment]
certo. Retirando espaço. Quando possível verificar a possibilidade de "espaço" não dar este problema.
Obrigada
