### ISSUE TITLE
Apresentação do conteúdo marcado com a tag "product" nas versões beta e HTML

### ISSUE THREAD

**Issue by javani** [scieloorg/Web#252]
Conteúdo marcado em product não aparece corretamente na versão HTML e Beta.
No HTML o dado de autor é suprimido da referência e na versão beta o dado não aparece.

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0034-75902015000200232&lng=en&nrm=iso&tlng=pt

http://www.scielo.br/article_plus.php?pid=S0034-75902015000200232&tlng=pt&lng=en

O arquivo XML foi enviado por email

**Comment by robertatakenaka** [comment]
@javani : o xml está assim (não há autor, somente editor, e está sendo apresentado).

```
<product product-type="book">
                                <inline-graphic xlink:href="0034-7590-rae-55-02-0232-gf01.tif"/>
                                <person-group person-group-type="editor">
                                        <name>
                                                <surname>Bucheli</surname>
                                                <given-names>Marcelo</given-names>
                                        </name>
                                        <name>
                                                <surname>Wadhwani</surname>
                                                <given-names>R. Daniel</given-names>
                                        </name>
                                </person-group>
                                <source>ORGANIZATIONS IN TIME: History, Theory, Methods</source>
                                <year>2014</year>
                                <publisher-name>Oxford University Press</publisher-name>
                                <publisher-loc>Oxford</publisher-loc>
                                <size units="pages">338 p</size>
                        </product>
```

**Comment by javani** [comment]
@robertatakenaka é um autor do tipo editor. Pode ocorrer de ser compiler também. Havendo person-group ele não deveria aparecer na referência?

**Comment by javani** [comment]
Na página beta eu não localizei.

**Comment by robertatakenaka** [comment]
@javani: na página do texto está: 
ORGANIZATIONS IN TIME: History, Theory, Methods. Bucheli, Marcelo; Wadhwani, R. Daniel. (2014). Oxford: Oxford University Press, 2014, 338 pp. 

Bucheli, Marcelo; Wadhwani, R. Daniel. = editores

**Comment by robertatakenaka** [comment]
@javani : na página nova realmente não tem.

**Comment by javani** [comment]
@robertatakenaka ele muda a ordem.... não tinha notado.

**Comment by robertatakenaka** [comment]
@javani: A ordem foi feita de acordo com o ticket https://github.com/scieloorg/Web/issues/202
