### ISSUE TITLE
Dados identificados pelo elemento <attrib> não aparecem no site SciELO

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/Web#259]
Verificamos que os dados identificados pelo elemtno ```<attrib>```em figuras, tabelas etc são suprimidos do site scielo.br e homolog.xml.scielo.br. Veja:

**dado marcado no XML**

![attribbs](https://cloud.githubusercontent.com/assets/4397365/7660713/f4bbec9a-fb22-11e4-90a5-798f55fea614.jpg)

**no site scielo**

![statrtibs](https://cloud.githubusercontent.com/assets/4397365/7660770/7ff3302a-fb23-11e4-9355-2a42df91505b.jpg)

Ver em: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-40362015000200367&lng=en&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
relacionada com #261
