### ISSUE TITLE
<attrib> não funciona em http://homolog.xml.scielo.br/

### ISSUE THREAD

**Issue by marciamorgan** [scieloorg/Web#261]
A indicação da fonte de uma imagem identificada com  <attrib> não aparece em homolog.xml.scielo.br

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1518-70122015000100003&lng=pt&nrm=iso&tlng=pt#f01

```<fig id="f01">
            <label>Figura 1</label>
            <caption>
               <title>Árvore Hierárquica com ramos distintos.</title>
            </caption>
            <graphic xlink:href="1518-7012-inter-16-01-0027-gf01.tif"/>
            <attrib>Fonte: Kupfer; Hasenclever, 2002</attrib>
         </fig>```

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#attrib

**Comment by robertatakenaka** [comment]
@marciamorgan : por que o ticket foi fechado?

**Comment by marciamorgan** [comment]
Roberta,

eu vi agora que a Letícia já tinha aberto um ticket relatando o mesmo
problema. Deixo aberto de qualquer maneira?

2015-05-25 15:34 GMT-03:00 Roberta Takenaka <notifications@github.com>:

> @marciamorgan <https://github.com/marciamorgan> : por que o ticket foi
> fechado?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scieloorg/Web/issues/261#issuecomment-105285857>.
>



-- 
Att.,
Marcia Morgan
SciELO Brasil
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org
_____________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil

**Comment by robertatakenaka** [comment]
entendi. Eu achei que se tratava do ticket que ela já tinha aberto. Você
pode anotar que é duplicated. É sempre bom comentar o motivo de fechar.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-05-25 15:36 GMT-03:00 marciamorgan <notifications@github.com>:
