### ISSUE TITLE
Tag de arquivo Errata deve gerar link | site e homologs

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/Web#277]
É inserido em todas as erratas (article-type="correction") a tag, exemplo:

```<related-article related-article-type="corrected-article" id="RA1" xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="10.5935/abc.20140077" ext-link-type="doi"/>```

```<related-article related-article-type="corrected-article" id="RA1"
                                xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="10.5935/abc.2013S006"
                                ext-link-type="doi"/>``

Está inserção deveria gerar um link da Errata com o artigo corrigido através do número de DOI inserido, no site SciELO e nos homologs.

Informações sobre a validação da tag:
- A Tag Related é obrigatória em todos os arquivos do tupo "correction"
- Um XML de Errata pode ter mais de uma tag de related.
- A tag de related aceita informações vol="xxx" e page="xxx", mas não são obrigatórias
- Erratas podem estar em formato AOP ou Arquivo de Fascículo

Ver documentação de Errata no SPS link: http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/narr/errata.html#errata

Exemplos de XML de Erratas:

Ex- AOP
arquivo: 1982-4327-paideia-1982-432725612015
V:\SciELO\serial\paideia\v25n61\1982-4327-paideia-25-61

DELTA V31N2

ERRATA: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-863X2015000200271&lng=pt&nrm=iso&tlng=en

DELTA V31N1

ARQUIVO CORRIGIDO: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-44502015000100261&lng=en&nrm=iso&tlng=es

Em fascículo
arquivo: 0006-8705-brag-74-2-239
V:\SciELO\serial\brag\v74n2\0006-8705-brag-74-2

ERRATA - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0006-87052015000200239&lng=en&nrm=iso&tlng=en

ARQUIVO CORRIGIDO - http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0006-87052014000400010&lng=en&nrm=iso&tlng=en


Errata:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2015002300445&lng=en&nrm=iso&tlng=pt
ARTIGO CORRIGIDO:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2014005040173&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@RPostalli : por favor, incluir na descrição o link da errata e do artigo relacionado.

**Comment by robertatakenaka** [comment]
@RPostalli : onde ficariam os links para a errata no HTML, no site?

**Comment by RPostalli** [comment]
O correto seria ficarem em back, onde é descrito a Errata do artigo "corrigido" (em fn-group).

Já na própria Errata o correto seria ficarem em front onde é inserido a tag de related. (Como errata não tem indicação de autor e aff, poderia ficar abaixo no título "Errata")

**Comment by robertatakenaka** [comment]
Exemplo real:
Errata:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2015000500012&lng=en&nrm=iso&tlng=en

Arquivo com erro:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0066-782X2013003600001&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@javani,@leticiaquino, @RPostalli : podemos deixar assim? Estou retomando o assunto.

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-44502015000100261&lng=en&nrm=iso&tlng=es
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0103-863X2015000200271&lng=pt&nrm=iso&tlng=en

**Comment by leticiaquino** [comment]
@robertatakenaka a meu ver ficou muito bom!

**Comment by javani** [comment]
@robertatakenaka para mim está tudo certo. Pode atualizar em produção.

**Comment by javani** [comment]
@robertatakenaka a caixa de texto que havia no artigo (dizendo que o artigo tinha uma errata) parou de funcionar. Só aparece na errata para o artigo, a volta não. Você poderia verificar?

**Comment by robertatakenaka** [comment]
@javani: por favor, inclua um link de exemplo.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by javani** [comment]
@robertatakenaka estes que estão no ticket estavam funcionando. Veja que só a errata agora tem o quadrinho, no artigo corrigido não há mais.
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-44502015000100261&lng=en&nrm=iso&tlng=es
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0103-863X2015000200271&lng=pt&nrm=iso&tlng=en
