### ISSUE TITLE
Verificar marcação de data dupla na referência

### ISSUE THREAD

**Issue by salgadoe** [scieloorg/Web#298]
No arquivo Juliano Neves, revista Cadernos Nietzsche v36n1 ao marcar a referência abaixo apresentou erro na data:

[ref id="r7" reftype="book" status="valid"][authors role="nd"][pauthor][surname]NIETZSCHE[/surname], [fname]F.[/fname][/pauthor][/authors] [source]Sämtliche Werke. Kritische Studienausgabe[/source]. [publoc]Berlin[/publoc]/[publoc]New York[/publoc]: [pubname]Walter de Gruyter[/pubname], 	[date dateiso="19780000" specyear="1967-1978"]1967-1978[/date], [extent]15v[/extent]. [/ref]

O erro apresentado no relatório:
year	OK	1967-1978
given-names	OK	F.
year	FATAL ERROR	is not a number nor in an expected format.

att
eliana

**Comment by robertatakenaka** [comment]
@salgadoe : este ticket não é do produto Web. Abrir este ticket em PC-Programs.
