### ISSUE TITLE
Problema com notas na visualização em HTML do site

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/Web#299]
Na visualização em HTML dos artigos no site, ao clicar em uma nota no texto, a página não vai para a respectiva nota no final do artigo.

Exemplos:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-62762015000100001&lng=en&nrm=iso&tlng=pt
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1983-68212014000200003&lng=en&nrm=iso&tlng=pt
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-83332015000100031&lng=en&nrm=iso&tlng=en

Obs.: as citações no texto funcionam corretamente levando para a respectiva citação no final do artigo.

**Comment by javani** [comment]
@robertatakenaka este problema voltou a ocorrer. Não faz o link para a nota corretamente.
