### ISSUE TITLE
<label> de boxed-tex não aparece no site

### ISSUE THREAD

**Issue by suelylc** [scieloorg/Web#302]
Também não faz link entre a chamada no corpo do texto e o ```<boxed-text>```

```<boxed-text id="b01">
                    <label>Quadro 1</label>
                    <caption>
                        <title>Critérios de avaliação de qualidade de um <italic>software</italic>.
                            Fonte: NBR 13.596<xref ref-type="bibr" rid="B008"
                            ><sup>8</sup></xref></title>
                    </caption>
                    <table-wrap position="float">
                        <table frame="hsides" rules="groups">
                            <col width="22.65%"/>
                            <col width="33.91%"/>
                            <col width="43.44%"/>
                            <thead>```

Apresetação no site:

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1807-25772015000300163&lng=en&nrm=iso&tlng=pt

**Comment by lpanebr** [comment]
Nossa resolver isso vai nos ajujdar MUUUUITO!!!!

Obrigado pela atenção criando o ticket!

**Comment by lpanebr** [comment]
desculpe perturbar novamente mas se o @gustavofonseca  me apontar em qual(is) arquivo(s) devo mexer posso tentar contribuir com um XSLT.

Se essa colaboração der certo posso fazer isso com mais frequência!

Para mim vai compensar muito ajudar a resolver isso do que ficar documentando exceções no do nosso fluxo para realizar modificações pós export no XML...

Obrigado!

**Comment by gustavofonseca** [comment]
Eu gosto bastante da idéia da colaboração, mas infelizmente não sou a pessoa mais indicada para te ajudar pois tb não estou familiarizado com a base de códigos desse projeto. Acho que vc deveria falar com a @robertatakenaka ou dar uma fuçada sem medo de ser feliz =]

**Comment by robertatakenaka** [comment]
@lpanebr : neste caso, para este ticket, seria a htdocs/xsl/pmc/v3.0/scielo-fulltext.xsl

**Comment by lpanebr** [comment]
Ah, que legal @robertatakenaka ! :+1: 

não estou conseguindo transformar com o saxon 6.5.5:

    java -jar /home/lpanebr/Applications/saxon6-5-5/saxon.jar -o fulltext.html input.xml scielo-fulltext.xsl

pois da erro deviso a diversas variáveis não definidas..

    Variable langtext has not been declared

Me sinto meio bobo... se me der uma dica prometo que ajudo!

PS: meus XSLTs normalmente não dão esse problema pois são executados dentro do nosso software de exportação então eu nem precisei aprender a lidar com isso ainda...  sorry.. :-/

**Comment by robertatakenaka** [comment]
De fato, não seria simples porque na estrutura que temos no Web, há várias
xsl incluidas, sendo que scielo-fulltext.xsl é uma delas.
Se você tem o site scielo instalado localmente acabaria ficando mais fácil.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-07-02 14:53 GMT-03:00 Luciano <notifications@github.com>:

**Comment by lpanebr** [comment]
:-( não tenho.... (não ainda anyway...) rola um how-to???  :-D

**Comment by robertatakenaka** [comment]
http://docs.scielo.org/projects/scielo-site/en/latest/

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by lpanebr** [comment]
:-D

Vai demorar um pouco (vou tirar férias semana que vem) mas vou colocar isso pra rodar em um docker container e ai o bixo vai pegar!

**Comment by robertatakenaka** [comment]
Na verdade, você não precisaria do site em funcionamente. Bastaria ter a
pasta htdocs/xsl.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by lpanebr** [comment]
hmm..   ai facilita! Vou ativar o modo hacker e dar um jeito. ;-)

Obrigado!

**Comment by robertatakenaka** [comment]
@suelylc : me parece que este problema foi resolvido? confirma?

**Comment by suelylc** [comment]
@robertatakenaka apresentação ok

**Comment by lpanebr** [comment]
Oi @robertatakenaka 

Creio que a apresentação do *Quadro 1* no [link original do ticket](http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1807-25772015000300163&lng=en&nrm=iso&tlng=pt) **foi resolvida internamente modificando o XML original**.

A parte do [XSL no fulltext que transforma o boxed-text](https://github.com/scieloorg/Web/blob/master/htdocs/xsl/pmc/v3.0/scielo-fulltext.xsl#L816) não teve alteração recente.

**Comment by lpanebr** [comment]
Oi @robertatakenaka 

Baixei o repositório scieloorg/Web e tentei rodar uma transformação usando o Oxygen conforme você orientou mas está dando erro "Attribute name is not allowed on this element" conforme imagens abaixo no `htdocs/xsl/sci_arttext.xsl`:

![image](https://cloud.githubusercontent.com/assets/129185/8932109/4056eefc-3511-11e5-8e3c-72d6b9e340fe.png)

![image](https://cloud.githubusercontent.com/assets/129185/8932115/52d654b4-3511-11e5-84af-e5310d66008d.png)

Tem alguma ideia do que pode ser? Desculpe perturbar mas é que eu gostaria mesmo de tentar contribuir..

**Comment by fabiobatalha** [comment]
@lpanebr 

Olá Luciano, existe um erro nessa XSL. Troque o atributo name para mode. Vou verificar o efeito colateral deste erro em nosso site.

**Comment by lpanebr** [comment]
Obrigado @fabiobatalha agora melhorou mas agora a language não está sendo detectada apesar se estar no XML:

    Failure reading file:/home/lpanebr/mysites/webdev/public/Web/htdocs/xml//translation.xml: no more input

**Cabeçalho do XML:**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE article PUBLIC "-//NLM//DTD JATS (Z39.96) Journal Publishing DTD v1.0 20120330//EN" "JATS-journalpublishing1.dtd">
<article xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:mml="http://www.w3.org/1998/Math/MathML" article-type="research-article" dtd-version="1.0" specific-use="sps-1.1" xml:lang="pt">
```

**Estou rodando o seguinte comando a partir da pasta Web:**
```bash
$ pwd
~/mysites/webdev/public/Web
$ java -jar ~/pathPara/saxon6-5-5/saxon.jar -o ~/pathDeSaida/out.html ~/pathParaXML/input.xml htdocs/xsl/sci_arttext.xsl
```

**E resulta no erro:**
![image](https://cloud.githubusercontent.com/assets/129185/9142648/85a4890c-3d17-11e5-8709-9ab6ad3e0a6f.png)

Desculpe a ignorÂncia aqui.. se puder dar uma luz agradeço!
