### ISSUE TITLE
Tag de material suplementar em <front> não funciona no site e homologs.

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/Web#303]
A tag que esta documentada no link do SPS "http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset.html#supplementary-material" de material suplementar em PDF em ```<front>```, exemplo da tag:

```<supplementary-material id="suppl01" mimetype="application" mime-subtype="pdf" xlink:href="0101-2061-cta-35-1-38-suppl01.pdf"/>```

Não está funcionando no site scielo link: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0101-20612015000100038&lng=en&nrm=iso&tlng=en#t01

nem homolog.xml no link: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0101-20612015000100038&lng=en&nrm=iso&tlng=en

Averiguar XML "0101-2061-cta-35-1-38" no caminho: V:\SciELO\serial\cta\v35n1\0101-2061-cta-35-1

**Comment by robertatakenaka** [comment]
@RPostalli : onde deve ser apresentado no texto?

**Comment by RPostalli** [comment]
No caso do exemplo o material é comentado no texto de <body>, mas não é inserido no PDF do artigo. Neste caso pode-se utilizar a tag de material suplementar em <front> já que ele não consta no PDF original.

**Comment by robertatakenaka** [comment]
@RPostalli : Sim, mas no HTML, no site, onde ficaria este dado?

**Comment by RPostalli** [comment]
Eu não sei. nunca vi um material suplementar em front no site SciELO. Pelo o que é descrito no SPS a localização da tag, o correto seria aparecer abaixo das afiliações (já que notas de autor aparecem em sempre em back). Não?!

**Comment by robertatakenaka** [comment]
@RPostalli : Sim, é uma possibilidade.
