### ISSUE TITLE
Ajustar datestamp em protocolo OAI.

### ISSUE THREAD

**Issue by fabiobatalha** [scieloorg/Web#310]
O datastamp do header de um registros deve estar relacionado a data de entrada/atualização no SciELO e não a data de publicação do documento no periódico.

**Comment by mmalmeida** [comment]
O código fonte está nalgum dos projectos do github? Se me der uma indicação de onde está poderei tentar ajudar a resolver o ticket.

**Comment by mmalmeida** [comment]
Bom dia @fabiobatalha . Gostaria de saber se há alguma previsão para o fecho deste ticket, e se posso ajudar na sua resolução para o fecharmos o mais brevemente possível.

**Comment by fabiobatalha** [comment]
@robertatakenaka @ednilson 
Roberta e Edy, para atendermos essa demanda será necessário criar um indice novo a partir do campo v91/v93 onde v706=h.

70 0 mpl,if v706='h' then 'UPDATEDT=',if p(v93) then,v93,else,v91,fi/, fi                /* oai-pmh - new and updated documents - SciELO.org */

Por favor confirmar/validar para que eu possa incluí-lo nos processamentos SciELO.

**Comment by ednilson** [comment]
@fabiobatalha  @robertatakenaka 

Os campos v91 e v93 são gravados no registro tipo O,  anterior ao H. Então, é necessário fazer um REF LOOKUP para o registro anterior. O formato ficaria assim:

70 0 mpl,if v706='h' then 'UPDATED=',ref((mfn-1),if p(v93) then v93 else v91 fi) / fi   /* oai-pmh - new and updated documents - SciELO.org */

Nos testes notei que em alguns o v93 contém também a hora de atualização com 4 dígitos (hhmm), vejam:

UPDATED=20151015 1131
UPDATED=20151001
UPDATED=20150820 0816
UPDATED=20150811
UPDATED=20150817 0850

Pegunto: Devo manter a hora ou posso fazer um slice de 0 a 7 para obter somente yyyymmdd?

**Comment by ednilson** [comment]
@fabiobatalha @robertatakenaka 

Ok, vamos manter somente YYYYMMDD.

70 0 mpl,if v706='h' then 'UPDATED=',ref((mfn-1),if p(v93) then v93*0.7 else v91*0.7 fi) / fi /* oai-pmh - new and updated documents - SciELO.org */

**Comment by ednilson** [comment]
@fabiobatalha @robertatakenaka 

corrigindo:
70 0 mpl,if v706='h' then 'UPDATED=',ref((mfn-1),if p(v93) then v93\*0.7 else v91\*0.7 fi) / fi /* oai-pmh - new and updated documents - SciELO.org */

**Comment by mmalmeida** [comment]
Bom dia,

Alguma estimativa para o fecho do ticket?
Obrigado!

**Comment by fabiobatalha** [comment]
Miguel,

Estimamos terminar esta semana.

A mudança requer reconfiguração e reprocessamento das bases SciELO. As
bases já foram atualizadas, os desenvolvimentos devem tomas mais 1 ou 2
dias.

Att,

**Comment by robertatakenaka** [comment]
@fabiobatalha @ednilson 
O índice usado para o OAI é mais completo:
15 0 mpl,if v706='h' then 'DTH=',v65*0.4, if v65*4.2 = '00' then, '01', else v65*4.2, fi, '01=',v35,s(f(val(v936^o)+10000,1,0))*1.4,s(f(val(v121)+100000,1,0))*1.5 fi,

Então deveria ser:
90 0 mpl,if v706='h' then 'OAITS=',ref(mfn-1,if p(v93) then if val(v93*0.8) > val(v91) then v93*0.8 else v91 fi else v91 fi),'=',v35,s(f(val(v936^o)+10000,1,0))*1.4,s(f(val(v121)+100000,1,0))*1.5 fi, fi

No lugar de:
90 0 mpl,if v706='h' then 'UPDATED=',ref((mfn-1),if p(v93) then v93 else v91 fi) / fi /* oai-pmh - new and updated documents - SciELO.org */

**Comment by robertatakenaka** [comment]
@fabiobatalha , @ednilson : para atender o ticket, as mudanças devem ser:

1. O índice a ser gerado deve ser `OAITS=<data de processamento>=PID do artigo sem S no início`. Isso é para garantir o resumptionToken.

2. Além disso, deve ser modificado o valor de datestamp tanto nos XML do OAI e OAI agris, usar a data de processamento (v91 ou v93*0.8, o que for mais recente)

3. Corrigir o termo do keyrange no .xis, ou seja, trocar DTH por OAITS. No entanto, preservar o índice DTH e a consulta por DTH=.

4. Alteração da validação do resumptionToken. (scielo-oai.php)

5. O que foi estranho é que o agris obriga o parâmetro set. Sendo assim, a consulta é sempre no PID dos artigos e não na data de processamento ou publicação. Está correto isso?

**Comment by fabiobatalha** [comment]
Mas você pode ter o setspec + a data como filtro, não pode?

2015-11-23 15:31 GMT-02:00 Roberta Takenaka <notifications@github.com>:

**Comment by robertatakenaka** [comment]
Então, mas pelo que vi no agris, ao ter o set, está anulando o from, ou
seja, from é ignorado. Isto está correto ou incorreto? Qual é a lógica do
agris? O set no OAI, não testei, mas provavelmente é igual a do agris.
Atualmente a diferença é que no agris o set está como obrigatório e no OAI
não.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-11-23 16:21 GMT-02:00 Fabio Batalha <notifications@github.com>:

**Comment by fabiobatalha** [comment]
Na verdade, por se tratar do protocolo OAI, o set não deveria ser
obrigatório em nenhum dos metadata_prefix. Acho melhor tirar essas
obrigatoriedade.

2015-11-23 16:26 GMT-02:00 Roberta Takenaka <notifications@github.com>:

**Comment by ednilson** [comment]
Novos ajustes foram aplicados por @robertatakenaka em #363
