### ISSUE TITLE
Em Errata aparece o título em cada parágrafo (desconfigurado)

### ISSUE THREAD

**Issue by RPostalli** [scieloorg/Web#311]
Roberta eu acho que isso já havia sido corrigido mas por algum motivo voltou a acontecer.

Veja exemplos: (De um control F na palavra "Erratum")
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-21002014000200004&lng=en&nrm=iso&tlng=en 

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0103-05822014000400342&lng=en&nrm=iso&tlng=en

Se o texto em ```<fn>``` tiver 15 parágrafos a palavra "erratum" é replicada na frente de cada parágrafo e não fica uma indicação de seção, o que significa que o site está excluindo a informação de ```<label>``` ou ```<title>``` inserida em ```<fn>```.

OBS: Para o título da seção Errata deve ser considerado as duas possibilidades de:

```<fn-group>
			<fn fn-type="other">
				**<title>Errata</title>**
				<p>...```

Ou

```<fn-group>
			<fn fn-type="other">
				**<label>Errata</label>**
				<p>...```

OBS2: Este "defeito" também ocorre em homolog.xml.

**Comment by robertatakenaka** [comment]
@RPostalli : Para este caso, o ideal é usar title no lugar de label. Usando title, será colocado o title em uma linha com destaque e na outra linha o texto. Usando label, será colocado o label na mesma linha do texto e ficará sobrescrito. De qualquer forma, o site não está considerando a existência de title ainda
