### ISSUE TITLE
Responsável pelo artigo marcado como "editor" não aparece no sumário - Site e Homolog

### ISSUE THREAD

**Issue by renatogaldino** [scieloorg/Web#321]
Quando a tag `<contrib contrib-type="editor">` e utilizada com o valor diferente de *author*, o nome do responsável não aparece no respectivo sumário. A informação é apresentada somente no texto completo. [Ver exemplo.] (http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1677-553820150003&lng=en&nrm=iso)

**Obs:** O link do exemplo pode ter sido corrigido após a abertura do ticket. Segue imagem:

**Sumário**

![exemplo](https://cloud.githubusercontent.com/assets/11942249/9409763/0aebf1a0-47f3-11e5-988b-6e1b1091744a.jpg)

**Full text:**

![full text](https://cloud.githubusercontent.com/assets/11942249/9409842/8089c1c6-47f3-11e5-831b-b338184c40fa.jpg)

**XML**

```
<contrib-group>
                <contrib contrib-type="editor">
                    <name>
                        <surname>Favorito</surname>
                        <given-names>Luciano A.</given-names>
                    </name>
                    <degrees>MD, PhD</degrees>
                    <role>Associated Editor of International Braz J Urol</role>
                    <xref ref-type="aff" rid="aff1"/>
  </contrib>
```

**Comment by robertatakenaka** [comment]
@renatogaldino : Renato, é assim mesmo. Para editorial não é apresentado o nome do autor, quando identificado com algo diferente de "author".
