### ISSUE TITLE
site SciELO suprime informação contida em <comment>

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/Web#322]
Após comentários na lista de discussão. ver: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scielo-xml/i5wCr8CrXGA/iLw-ceLGDQAJ

Verifiquei que o site SciELO não reconhece o elemento ```<comment>``` e suprime o dado identificado nessa tag.
Veja que eu completei a marcação dos dados de product, mas mantive o ```<comment>``` para identificar a informação "Tese (Doutorado em Educação)":

``` xml
<product product-type="other">
    <person-group person-group-type="author">
        <name>
            <surname>GINO. A.</surname>
            <given-names>S</given-names>
        </name>
        </person-group>
        <source>Um estudo sobre as contribuições de um curso de formação continuada a partir das
               narrativas de professoras que ensinam matemática</source>
        <year>2013</year>
        <size units="pages">254 f</size>
        <comment>Tese (Doutorado em Educação)</comment>
        <publisher-name>Faculdade de Educação, Universidade Federal de Minas Gerais</publisher-name>
        <publisher-loc>Belo Horizonte</publisher-loc>
        <year>2013</year>
</product>
```

Em enviei para o homolog.xml.scielo e o resultado foi o mesmo, o site suprimiu a informação "Tese (Doutorado em Educação)" que estava identificada em ```<comment>```.

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0103-636X2015000200021&lng=en&nrm=iso&tlng=pt

Por gentileza, verificar a possibilidade de não suprimir dados que constam nesse elemento.

**Comment by robertatakenaka** [comment]
GINO. A., S Um estudo sobre as contribuições de um curso de formação continuada a partir das narrativas de professoras que ensinam matemática. . 2013. 254 f. Tese (Doutorado em Educação). Faculdade de Educação,Universidade Federal de Minas Gerais. Belo Horizonte. 2013.
