### ISSUE TITLE
How to cited this article: formato APA - 6ª edição

### ISSUE THREAD

**Issue by javani** [scieloorg/Web#323]
O formato APA na página do SciELO aparece da seguinte forma:
Electronic Document Format(APA)
Robinson, Tamara B., & Swart, Cheruscha. (2015). Distribution and impact of the alien anemone Sagartia ornata in the West Coast National Park. Koedoe, 57(1), 1-8. Retrieved September 03, 2015, from http://www.scielo.org.za/scielo.php?script=sci_arttext&pid=S0075-64582015000100001&lng=en&tlng=en. 10.4102/koedoe.v57i1.1246.

Quando o artigo apresenta número de DOI a url de consulta é desconsiderada:
http://nova.campusguides.com/apa

Quick Examples of Resources Retrieved Electronically:
Using APA Style Guide to Electronic References (2012)
 1. Journal article with DOI assigned, one author.
 **** Preferred format for DOI number if using the APA Style Guide to Electronic References (2012):

 Hai-	
Qiang, M., Su-Mei, W., Da, Z.,  Jun-Tao, C., Ling-Ling, J., 
Yan-Xue, H., & Ling-An, W. (2014). Chinese Physics Letters,
21(10), 1961-1987.  http://dx.doi.org/10.0256-307X/21/1961

NOTE: If using the APA 6th ed., use doi:10.0256-307X/21/1961

Smith, 	
J. (2010). An interdisciplinary approach to preparing
early intervention professionals: A university and
community collaborative initiative. Teacher Education 
and Special Education, 33(2), 131-142. http://dx.doi.org
/10.1177/088840640.9357546 

NOTE: If using the APA 6th ed., use doi:10.1177/088840640
.9357546 

The DOI format with a hyperlink is preferred in the APA Style Guide to Electronic Reference (2012). The APA guide says that the old format is also accepted. However, it no longer is preferred. 
Correct:    
doi:10.4018/IJDET (format recommended in the APA 6th ed.)
http://dx.doi.org/10.4018/IJDET (format recommended in the APA Style Guide)
Incorrect:     

http://doi:10.4018/IJDET
doi:http://dx.doi.org/10.4018/IJDET
Retrieved from http://dx.doi.org/10.4018/IJDET

**Comment by robertatakenaka** [comment]
@javani: Ficou o seguinte:


Formato Documento Eletrônico(APA)
Marchon, Fabio Lennon, & Fantinato, Maria Cecília. (2015). Possibilidades Filosóficas em Etnomatemática. Bolema: Boletim de Educação Matemática, 29(52), 549-567. https://dx.doi.org/10.1590/1980-4415v29n52a07

(Ver página: http://homolog.xml.scielo.br/scielo.php?script=sci_isoref&pid=S0103-636X2015000200008&lng=pt&tlng=pt)

**Comment by javani** [comment]
Oi Robs,

Me parece bem.

Grata,



Sent with MailTrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

Em 3 de setembro de 2015 15:22, Roberta Takenaka <notifications@github.com>
escreveu:
