### ISSUE TITLE
Supressão de suffix na apresentação do nome do autor

### ISSUE THREAD

**Issue by javani** [scieloorg/Web#328]
Suprime o dado marcado em suffix para autoria de artigo no sumário e em como citar.

http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1983-211720150002&lng=en&nrm=iso

Marcação no XML:
![image](https://cloud.githubusercontent.com/assets/912953/9737354/9995fefa-561c-11e5-864f-8b0428348fc9.png)

No sumário:
![image](https://cloud.githubusercontent.com/assets/912953/9737384/c04868ee-561c-11e5-9830-76c4140fa3f2.png)

No artigo está aparecendo junto com com o último suobrenome:
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1983-21172015000200483&lng=en&nrm=iso&tlng=pt
![image](https://cloud.githubusercontent.com/assets/912953/9737406/e18dcb48-561c-11e5-8230-24e4e8cc2235.png)

**Comment by robertatakenaka** [comment]
@javani: por favor, verifique o XML.

O XC espera que o suffix e o prefix esteja dentro de name e não fora. Qual
é o correto? No caso deste arquivo o `<suffix>` existe fora do `<name>`

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by javani** [comment]
@robertatakenaka vc está certa. Não tinha atentado para este detalhe
