### ISSUE TITLE
Apresentação de label junto ao autor e afiliação quando inserido tag fechada no XML

### ISSUE THREAD

**Issue by suelylc** [scieloorg/Web#329]
Marcação de autor
![author](https://cloud.githubusercontent.com/assets/6921625/9772239/49f5c114-5711-11e5-9d8b-13385f4e9134.png)
Marcação da afiliação
![sem titulo](https://cloud.githubusercontent.com/assets/6921625/9772316/aeb018fc-5711-11e5-9fed-9f9b4cd67502.png)

Apresentação no site
![exemplo](https://cloud.githubusercontent.com/assets/6921625/9772259/67d7c84e-5711-11e5-8ced-954c5241609a.png)

**Comment by robertatakenaka** [comment]
Como está as afiliações no XML?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by suelylc** [comment]
Informação completa sobre o conjunto de instituições no ```<institution content-type="original">``` de ```<aff id="aff1">``` 
![aff](https://cloud.githubusercontent.com/assets/6921625/9772432/98f8b2fc-5712-11e5-84f1-eecdc5ec015a.png)
