### ISSUE TITLE
Histórico dos periódicos na grade de fascículos

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/Web#333]
![Uploading 01.jpg…]()
![Uploading 02.jpg…]()
![Uploading 03.jpg…]()

Na semana passada um novo periódico entrou na coleção Saúde Pública e ontem percebi que no histórico do periódico na grade de fascículos não está aparecendo a frase "Admitida na Coleção":

RESS na Coleção Saúde Pública: ver imagem 01
RESS na Coleção SciELO Brasil: ver imagem 02.

Essa frase sempre apareceu automaticamente com base na informação que nós colocamos no campo "Data de entrada" na Title antiga (ver imagem 3).

Vocês poderiam ver um jeito de fazê-la aparecer também quando usamos o SciELO Manager?

**Comment by robertatakenaka** [comment]
@francine-curivil: acredito que o problema não deve ser registrado em Web,
pois não é um problema a ser resolvido na aplicação do site, mas sim, ou no
scielo-manager, ou no delorean2isis.

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-09-17 15:19 GMT-03:00 francine-curivil <notifications@github.com>:

**Comment by francine-curivil** [comment]
@robertatakenaka 

Verdade! Abri outro no lugar correto:
https://github.com/scieloorg/scielo-manager/issues/1215
