### ISSUE TITLE
Erro na apresentação de Material suplementar

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/Web#354]
Os links que direcionam para o material suplementar  estão ficando grudado no site, porém na página beta está ok.

Homolog: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47572015005050026&lng=en&nrm=iso
![supp_dup_homolog](https://cloud.githubusercontent.com/assets/4633779/10824443/82b17068-7e47-11e5-90e2-ec00af823682.png)

XML:
![supp_dup](https://cloud.githubusercontent.com/assets/4633779/10824456/94c2a90c-7e47-11e5-8e05-f551c469fbc9.png)

Página beta:
![supp_dup_beta](https://cloud.githubusercontent.com/assets/4633779/10824468/9c9bb880-7e47-11e5-955f-385b84ccbccb.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo: Luana, o que está previsto é que dentro de
supplementary-material esteja somente texto, sem label e caption.
Pode tentar desta forma?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
Ok @robertatakenaka vou retirar e ver como fica a apresentação.

**Comment by luanaaraujo** [comment]
@robertatakenaka Fiz o teste, mas ficou da mesma forma: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47572015005050026&lng=en&nrm=iso&tlng=en

e depois que tirei na beta também fica com a apresentação errada: http://homolog.xml.scielo.br/article_plus.php?pid=S1415-47572015005050026&tlng=en&lng=en

E as tags de label e caption estão nos exemplos do SPS, acredito que não seja por isso.
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.2-branch/tagset.html#supplementary-material

**Comment by robertatakenaka** [comment]
@luanaaraujo: inclua dentro <p> e </p> em cada supplementary-material

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-10-29 15:32 GMT-02:00 luanaaraujo <notifications@github.com>:

**Comment by luanaaraujo** [comment]
@robertatakenaka coloquei <p> e mesmo assim em homolog fica grudado:
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47572015005050026&lng=en&nrm=iso&tlng=en

Porém na página beta fica correto: 
http://homolog.xml.scielo.br/article_plus.php?pid=S1415-47572015005050026&tlng=en&lng=en

**Comment by robertatakenaka** [comment]
@luanaaraujo: como ficou o XML? Colocou cada <supplement-material dentro de
<p> e </p>? Mostre aqui como foi feito

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
Mmm agora foi @robertatakenaka !!! Desculpa pela confusão, entendi que p era dentro e não fora!!
Valeu!

![correto](https://cloud.githubusercontent.com/assets/4633779/10844670/9af8ced6-7ee8-11e5-81e4-2e3c65989786.png)

![xml_correto](https://cloud.githubusercontent.com/assets/4633779/10844671/9e69fdba-7ee8-11e5-96d5-9e009aa9a7ac.png)

**Comment by robertatakenaka** [comment]
@luanaaraujo: que bom!

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639


2015-10-30 9:29 GMT-02:00 luanaaraujo <notifications@github.com>:
