### ISSUE TITLE
<inline-formula> em abstract

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#360]
Quando há <inline-formula> em <abstract> não abre o link do resumo em homolog http://homolog.xml.scielo.br/scielo.php?script=sci_abstract&pid=S1415-47572015005004105&lng=en&nrm=iso&tlng=en

Porém no texto completo aparece normalmente
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47572015005004105&lng=en&nrm=iso&tlng=en

XML: 
![inline_abstract](https://cloud.githubusercontent.com/assets/15328777/11249262/f8f391d2-8e0c-11e5-9ec0-c57d3e0180fc.png)

Homolog texto completo: 
![inline_abstract_homolog](https://cloud.githubusercontent.com/assets/15328777/11249293/226cfb84-8e0d-11e5-8aa8-a1f271b18735.png)

**Comment by robertatakenaka** [comment]
@alexxpsilva: Alex, para solucionar este ticket, além de correções no Web, houve também correção no XC (https://github.com/scieloorg/PC-Programs/issues/1863). Além disso, foi necessário reprocessar o artigo.
