### ISSUE TITLE
(Android) Fonte das seções em tamanho reduzido

### ISSUE THREAD

**Issue by alexxxmendonca** [scieloorg/Web#399]
Problema encontrado nos navegadores Android. A fonte das seções aparece em tamanho reduzido.

Exemplo: http://www.scielo.br/scielo.php?script=sci_issuetoc&pid=1517-970220150010&lng=en&nrm=iso

![untitled-2](https://cloud.githubusercontent.com/assets/4059679/12612368/4c728cca-c4d9-11e5-914f-fecf423e08c8.png)

O problema com outros periódicos, não somente no exemplo acima.

O problema não ocorre nos navegadores de Mac, Windows ou iOS, apenas no Android.

**Comment by fabiobatalha** [comment]
Alex,

O problema ocorreu utilizando qual brownser no Android?

Testamos com Android + Firefox e esta ok.

Att,

**Comment by alexxxmendonca** [comment]
Foi testado no Chrome.
