### ISSUE TITLE
[issuetoc] Consultar também sub-article/subject para definir a seção do sumário

### ISSUE THREAD

**Issue by Aleciom** [scieloorg/Web#404]
Notei que ao processar a revista rbep v5n3 com 3 idiomas diferentes para o <subject>
a seção fica duplicada no sumario eletrônico, (no caso de idioma diferentes de  Inglês, Português Espanhol) pra este caso foi o idioma francês. Veja o exemplo abaixo.
![sem titulo](https://cloud.githubusercontent.com/assets/15981383/12844029/0ffcbdda-cbe4-11e5-9b5b-54cd79f39d89.png)
Veja o XML abaixo.
![sem titulo](https://cloud.githubusercontent.com/assets/15981383/12844224/35efd4ae-cbe5-11e5-862a-49542368d362.png)

**Comment by robertatakenaka** [comment]
@Aleciom :
Verifiquei que o artigo "Dynamiques Cr�atives d'un Patrimoine Immat�riel: la transmission orale du..." está sem seção, por favor, verifique.
E quanto à seção do artigo mencionada no ticket aparentemente você conseguiu resolver. Confirma?

**Comment by Aleciom** [comment]
Referente o problema mencionado no ticket,  este  foi resolvido, pois só foi possível corrigi-lo quando o <subject> encontra-se nos idiomas português, espanhol ou Inglês, quando não está nesse padrão de idioma ocorre esse problema com a interface do homolog  , o sistema não adequa sozinho para um idioma cabível , o problema com o artigo Dynamiques Cr�atives d'un Patrimoine Immat foi o mesmo , ele divergiu com o sumario por que o <subject>  estava em francês. Penso que seria interessante que o sistema fizesse essa adequação automática, pois sempre quando surgi esse problema precisamos fazer manualmente.

**Comment by robertatakenaka** [comment]
@Aleciom : sim, de fato, só são aceitos como idiomas do site atual os idiomas pt, en, es, então nem há como registrar uma seção que não esteja neste idiomas.

**Comment by renatogaldino** [comment]
@robertatakenaka não seria interessante considerar o que o @Aleciom disse:

>Penso que seria interessante que o sistema fizesse essa adequação automática, pois sempre quando surgi esse problema precisamos fazer manualmente.

Visto que quando há outro idioma - fora pt, en, es - temos que adequá-lo manualmente.

A interface poderia por exemplo adequar ao idioma correspondente - dentre os três do site atual - em `<sub-article>`, sendo que, o Homolog considera somente o idioma de `<article>`, causando dessa maneira o erro citado: o artigo fica fora de seção.

**Comment by robertatakenaka** [comment]
@renatogaldino, @Aleciom : as seções que são apresentadas no site são aquelas que estão registradas na base "issue" e só se registram os idiomas: pt, es, en.

**Comment by renatogaldino** [comment]
@robertatakenaka não me refiro as seções registradas na base "issue", **e sim a adequação da interface**, dessa maneira não teríamos que fazer uma "gambiarra" para que o artigo em outro idioma entre em uma seção registrada.
A interface poderia considerar o elemento `<subject>` em `<article>` e `<sub-article>` por exemplo, resolvendo o problema sem a necessidade de "gambiarra".

**Comment by robertatakenaka** [comment]
@renatogaldino: entendi. No entanto, seria possível somente se no XML também houvesse subject em um dos idiomas: pt, en, es.

**Comment by renatogaldino** [comment]
Sim @robertatakenaka é exatamente esse o caso.

**Comment by robertatakenaka** [comment]
@renatogaldino : gostaria de deixar claro que é uma limitação do site que existe hoje. No entanto, a modificação que farei para isso se ajustar automaticamente é no XC. O site realmente não tem como apresentar seções que não estejam registradas na base issue. Mas no site novo acredito que isso estará correto. Somente funcionará para artigos que tiverem seção em pt, en ou es. Se o artigo tiver somente uma seção e em um idioma que não seja pt, en, es, terá que ser preenchido em um destes idiomas.
