### ISSUE TITLE
equações minúsculas da rbef v38n1 em homolog.xml

### ISSUE THREAD

**Issue by marciamorgan** [scieloorg/Web#436]
Algumas equações do v38n1 da rbef estão muito pequenas e outras estão minúsculas em homolog.xml.

As imagens estão na proporção "correta" de +/- 20 px por "linha".

Exemplo: Eqs minúsculas 5, 7, 8, 9, 39, 41, 42 , 55, 62

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1806-11172016000100406&lng=en&nrm=iso&tlng=pt

(relacionado com #424)

**Comment by robertatakenaka** [comment]
@marciamorgan : como foi capturado do PDF as imagens estão estreitas na largura do PDF. Por equação se "espera" que não ocupem mais que 1 ou 2 linhas, por isso, elas ficam pequenas porque há um limite máximo de altura. Este limite foi posto porque para alguns artigos, por exemplo, o do ticket #242, provavelmente vão ficar gigantes. Vou verificar, aguarde.

**Comment by robertatakenaka** [comment]
@marciamorgan e @carolinatanigushi: Verifiquei que se não delimitar a altura de disp-formula (disp-formula-graphic) as equações da http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0001-37652014000100003&lng=en&nrm=iso&tlng=en, vão ficar muito grandes. Vou procurar um ponto de equilíbrio.

**Comment by lpanebr** [comment]
Penso que 120px de altura estragrará as equações de múltiplas linhas
enviadas em uma única imagem.

**Comment by robertatakenaka** [comment]
@lpanebr : Olá Luciano, de que forma estragará? Pode dar um exemplo?

**Comment by lpanebr** [comment]
Veja as equações multilinha neste artigo
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-40422010000600020

A equação 12 vai ficar com 120px de altura?

**Comment by robertatakenaka** [comment]
@lpanebr : obrigada pela sua contribuição. De fato, se esta equação estivesse em XML seria afetada.

**Comment by lpanebr** [comment]
Ah, então não entendi nada.. (rs). Eu achei que o problema seria justamente
com equações em imagem!

**Comment by robertatakenaka** [comment]
@lpanebr: Acho que entendeu, sim. Eu quis dizer que este artigo em particular me parece que veio como HTML, por isso não seria afetado (não veio como XML).

**Comment by lpanebr** [comment]
Ah.. ufa...

Então OK. Fico feliz em ter ajudado!
