### ISSUE TITLE
Revisão das FSTs

### ISSUE THREAD

**Issue by ednilson** [scieloorg/Web#442]
Esta revisão tem por objetivo reduzir a produção de chaves de buscas desnecessárias, reduzir o tamanho dos arquivos de índices e, principalmente, o tempo de processamento.

Verificar inicialmente:
fst/artigo.fst
fst/issue.fst
fst/title.fst

**Comment by robertatakenaka** [comment]
O índice TLN=... seria usado para indicar a existência texto do artigo em algum idioma, no entanto não existe v704^l. Para indicar se existe ou não o texto em determinado idioma, para alguns registros há os campos v601.
Então seria trocar:
14 0 mpl,if v706='p' and p(v704^l) then 'TLN=',v880,v704^l fi,
Por 
14 0 mpl,if v706='h' then if p(v601) then ('TLN=',v880[1],v601/) fi,('TLN=',v880,v40/) fi,
