### ISSUE TITLE
Link de errata em homolog

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#445]
No caso da jaos v24n1 o homolog.xml não apresenta o link pra direcionar para o artigo corrigido.

link homolo.xml: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en

Já em homolog.br o link aparece, além de ter criado um link para o próprio artigo da errata (jaos v24n1)

![jaos_errata](https://cloud.githubusercontent.com/assets/15328777/14362133/92f88a86-fcd4-11e5-99c9-48be66fe4b56.png)

Link do homolog.br: http://homolog.scielo.br/scielo.php?script=sci_arttext&pid=S1678-77572016000100106&lng=en&nrm=iso&tlng=en

Aparentemente a marcação no xml está correta.

**Comment by robertatakenaka** [comment]
@alexxpsilva : Por favor, incluir aqui o trecho do related-article do XML dos dois arquivos: errata e artigo corrigido.

**Comment by alexxpsilva** [comment]
Roberta, o arquivo corrigido não possui tag de related-article, somente uma nota com a informação de errata.


Trecho do arquivo da errata: ```<related-article related-article-type="corrected-article" id="RA1"
				xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="10.1590/1678-775720130468"
				ext-link-type="doi"/>```

**Comment by robertatakenaka** [comment]
@alexxpsilva :
O trecho 
```xml
<article-id pub-id-type="publisher-id" specific-use="previous-pid">S1678-77572014000500434</article-id>
```
que está no arquivo da errata: jaos/v24n1/1678-7757-jaos-24-1-0107.xml, me parece que não deveria existir.
Este PID indicado é do artigo e não do "ex" aop da errata. Se este trecho é para existir o valor S1678-77572014000500434 deveria ser do PID da errata aop.

Sugiro remover o trecho e enviar para o XC novamente.

**Comment by alexxpsilva** [comment]
@robertatakenaka  deu certo.
