### ISSUE TITLE
Erro ao acessar o Article References na caixa de serviços

### ISSUE THREAD

**Issue by rondinelisaad** [scieloorg/Web#468]
O acesso ao item "Articles References" na caixa de serviços está com erro de timeout para qualquer artigo. Eu fiz um teste no seguinte artigo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-86502014000300145&lng=en&nrm=iso&tlng=en
Analisando no arquivo php /var/www/scielo_br/htdocs/scieloOrg/php/reference.php na linha 65 há uma instrução onde ele faz uma pesquisa na base artigo, gerando assim uma URL http://homolog.scielo.br/cgi-bin/wxis.exe/?IsisScript=ScieloXML/sci_references.xis&database=artigo&gizmo=GIZMO_XML_REF&search=rp=<pid>
Eu fiz um teste no artigo citado acima:
http://homolog.scielo.br/cgi-bin/wxis.exe/?IsisScript=ScieloXML/sci_references.xis&database=artigo&gizmo=GIZMO_XML_REF&search=rp=S0102-86502014000300145
e ele deu o seguinte erro no apache error:
Timeout waiting for output from CGI script /var/www/scielo_br/cgi-bin/wxis.exe
Premature end of script headers: wxis.exe
Obs.: Eu percebi isso no SciELO Espanha e fui ver se isso replicava no BR e no homolog e vi que sim.

**Comment by robertatakenaka** [comment]
Havia erro ao obter as referências quando o artigo estava em XML ou quando o artigo não tinha referências. Havia erro na apresentação das referências na página.

**Comment by swarzesherz** [comment]
@robertatakenaka hola, al parece este error presiste http://www.scielo.org.mx/scieloOrg/php/reference.php?pid=S0188-77422016000100243&caller=www.scielo.org.mx&lang=es puede ser debido al revert que se hizo en el commit 9a807c8d
