### ISSUE TITLE
Problema nos links de pdf das retrôs

### ISSUE THREAD

**Issue by luanaaraujo** [scieloorg/Web#488]
O erro ocorre tanto no homolog.xml quando no site final. Ao clicar no link:

Texto completo disponível apenas em PDF.

Full text available only in PDF format.

Apresenta o seguinte erro:

![site final](https://cloud.githubusercontent.com/assets/4633779/15322661/6ece6428-1c14-11e6-9a88-2d561d066cc7.png)

Site final: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1983-21172002000200115&lng=en&nrm=iso&tlng=pt

Homolog: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1983-21172000000100088&lng=pt&nrm=iso

**Comment by robertatakenaka** [comment]
@luanaaraujo: como este link está no XML?

Roberta Takenaka

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FapUNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

**Comment by luanaaraujo** [comment]
```<body>
                  <p>Texto completo disponível apenas em PDF.</p>
                  <p>Full text available only in PDF format.</p>
         </body>```
