### ISSUE TITLE
Artigo relacionado aparecendo como artigo corrigido

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#492]
No homolog.sp os artigos marcados com a tag de related aparece como arquivos corrigidos, igual nos casos de erratas.

Link do homolog.sp: http://homolog.xml.scielosp.org/scielo.php?script=sci_arttext&pid=S0102-311X2016000500604&lng=en&nrm=iso&tlng=en

Visualização no homolog.sp

![csp_chamado](https://cloud.githubusercontent.com/assets/15328777/15678584/43a9edd2-2725-11e6-8ad3-cda9d146e6ed.png)

Marcação no XML

![csp_chamado1](https://cloud.githubusercontent.com/assets/15328777/15678628/7099c22c-2725-11e6-928b-d4d4e05c7ae2.png)

Já em homolog.br não aparece nenhuma informação de artigo relacionado.

Link do homolog.br: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2016000500604&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@alexxpsilva 
Por favor, verificar:
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2016000500604&lng=pt&nrm=iso&tlng=en

<img width="553" alt="captura de tela 2016-11-22 as 10 06 49" src="https://cloud.githubusercontent.com/assets/505143/20523315/96f14e5e-b09b-11e6-87fe-641830175089.png">

**Comment by alexxpsilva** [comment]
@robertatakenaka fiz o teste com o atributo editor e continua sem aparecer: http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-311X20160005&lng=pt&nrm=iso

![ticket_contrib](https://cloud.githubusercontent.com/assets/15328777/20525528/050c45be-b0a7-11e6-86f7-5042cffe83ee.png)

**Comment by robertatakenaka** [comment]
@alexxpsilva Por favor, validar se o ticket pode ser fechado

**Comment by alexxpsilva** [comment]
@robertatakenaka pode fechar, por favor.
