### ISSUE TITLE
Tag product - visualização de forma indevida

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/Web#496]
O article type book review está marcado dessa forma: 
`<product product-type="book">
                <person-group person-group-type="author">
                    <name>
                        <surname>PRICE</surname>
                        <given-names>Richard</given-names>
                    </name>
                </person-group>
                <source>The convict and the colonel</source>
                <year>1998</year>
                <publisher-loc>Boston</publisher-loc>
                <publisher-name>Beacon Press</publisher-name>
                <size units="pages">284</size>
            </product>`

E no homolog.xml está aparecendo assim:
![sem titulo](https://cloud.githubusercontent.com/assets/19777809/15822187/aa155648-2bca-11e6-8301-af7c0d1569cf.png)

O título aparece primeiro que o autor.

**Comment by natalieakemi** [comment]
No caso da rbcsoc v31n91 também está ocorrendo esse problema. 

Exemplos:

No homolog:
![image](https://cloud.githubusercontent.com/assets/19558447/16529924/cd19fdee-3f9b-11e6-96b8-4c49d7a74f72.png)

No xml:
 
![image](https://cloud.githubusercontent.com/assets/19558447/16529953/e3734316-3f9b-11e6-821a-48604563a1ea.png)

No Homolog:
![image](https://cloud.githubusercontent.com/assets/19558447/16529973/0c368510-3f9c-11e6-9672-58c92f7ce438.png)

No xml:
![image](https://cloud.githubusercontent.com/assets/19558447/16529982/168126ce-3f9c-11e6-8ecf-8a630375c9c2.png)

No Homolog:
![image](https://cloud.githubusercontent.com/assets/19558447/16529999/26cd1eac-3f9c-11e6-89b9-103e39695fbe.png)

No xml:
![image](https://cloud.githubusercontent.com/assets/19558447/16530004/2f687430-3f9c-11e6-8101-e59c47275fd6.png)

No Homolog:
![image](https://cloud.githubusercontent.com/assets/19558447/16530006/331ccdec-3f9c-11e6-8809-bd271a8017ef.png)

No xml:
![image](https://cloud.githubusercontent.com/assets/19558447/16530014/3ebac866-3f9c-11e6-8fd7-102f77bd44b0.png)

Obs.: No SPS diz que a tag `<product>` deve estar inserida antes de `<history>` ou depois de `<fpage>,` porém como se trata de rolling pass não existe essas tags no arquivo.

**Comment by robertatakenaka** [comment]
@RPostalli, @natalieakemi , @lucasssantos: 
A forma de apresentação atual foi definida em #202.
É realmente necessário mudar esta definição? Se sim, entendam que todos os product anteriormente publicados passarão a ser apresentados de acordo com esta nova apresentação.

**Comment by RPostalli** [comment]
O problema, é que esta tag esta se comportando de forma diferente. É
possível manter a ordem tal qual foi inserida no XML e não manter um padrão
específico? Isso seria melhor.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[*Atenção*: A versão 1.2 do SPS, foi descontinuada em 5 de abril. Por
gentileza, passem a utilizar a versão 1.3 ou 1.4 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 1 de julho de 2016 15:20, Roberta Takenaka <notifications@github.com>
escreveu:

**Comment by robertatakenaka** [comment]
@RPostalli: sim, chamo a atenção que uma vez definido ou redefinido, o site será mudado para todos os products. Então, se surgir um novo artigo e quiserem que ele seja apresentado diferente ainda, novas modificações seriam feitas, e de novo ia mudar para todos, não somente para este novo. Então, sugiro que pensem bem na solicitação para que ela não seja refeita várias vezes.

**Comment by RPostalli** [comment]
A Natalie fez uma revista que possui 4 arquivos com product, cada um foi
definido de forma diferente, o autor aparece no começo, depois no meio e
etc. O problema esta na inconstância atual da apresentação da tag. Vou
pedir para ela acrescentar o exemplo no ticket.

Considere por favor deixar a marcação na ordem na qual ela foi identificada
no XML, assim não interferirmos na norma escolhida para esta apresentação.
Se houver algum problema nos números passados corrigimos manualmente.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[*Atenção*: A versão 1.2 do SPS, foi descontinuada em 5 de abril. Por
gentileza, passem a utilizar a versão 1.3 ou 1.4 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 1 de julho de 2016 15:46, Roberta Takenaka <notifications@github.com>
escreveu:

**Comment by robertatakenaka** [comment]
@RPostalli, @natalieakemi , @lucasssantos: por favor, informar os links para os artigos correspondentes

**Comment by natalieakemi** [comment]
Seguem os links:

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-69092016000200701&lng=en&nrm=iso&tlng=pt

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-69092016000200702&lng=en&nrm=iso

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-69092016000200703&lng=en&nrm=iso

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0102-69092016000200704&lng=en&nrm=iso

**Comment by lucasssantos** [comment]
@robertatakenaka 
Agora apareceu da forma como foi marcado, obrigado!

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-71831998000200328

**Comment by robertatakenaka** [comment]
Me parece que está corrigido

**Comment by RPostalli** [comment]
Roberta, ainda falta a identificação de uma tag que eu acredito que você não considerou na primeira alteração que é a suffix.

Veja o primeiro autor o nome dele é: Alexandre Shigunov Neto 

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0034-75902016000500585&lng=en&nrm=iso&tlng=pt

PDF: http://homolog.xml.scielo.br/pdf/rae/v56n5/0034-7590-rae-56-05-0585.pdf

A informação em sufiix "Neto" é suprimida.

O tag de product tem que considerar:

suffix
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-suffix.html#suffix

prefix
http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-prefix.html#prefix

Caminha do arquivo no V:
V:\SciELO\serial\rae\v56n5\0034-7590-rae-56-05

**Comment by javani** [comment]
@robertatakenaka  a referência do item resenhado está apresentando pontuações indevidas. 
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2017001008001&lng=pt&tlng=pt
Orientação no SciELO PS
```xml
<product product-type="book">
        <person-group person-group-type="author">
            <name>
                <surname>ONFRAY</surname>
                <given-names>Michel</given-names>
            </name>
        </person-group>.
        <source>La comunidad filosófica: manifiesto por una universidad popular</source> Trad. e notas de
        <person-group person-group-type="translator">
            <name>
                <surname>Castro</surname>
                <given-names>Antonia García</given-names>
            </name>
        </person-group>.
        <publisher-loc>Barcelona</publisher-loc>:
        <publisher-name>Gedisa</publisher-name>,
        <year>2008</year>
        <size units="pages">155</size>p.
    </product>
```
O markup está gerando o XML:
```xml
	<product product-type="book">
				<person-group person-group-type="compiler">
					<name>
						<surname>Oliveira</surname>
						<given-names>RMS</given-names>
					</name>
				</person-group><bold>, organizadores.</bold><publisher-loc>Belo Horizonte</publisher-loc><bold>:</bold><publisher-name>Fino Traço/Universidade Federal do Recôncavo da Bahia</publisher-name><bold>;</bold><year>2016</year><bold>.</bold><size units="pages">222</size><bold>p. ISBN</bold><isbn>978-85-67589-13-8</isbn>
			</product>
```

![image](https://user-images.githubusercontent.com/912953/32959153-d4bf544c-cba7-11e7-97df-d6335ff09bbd.png)
