### ISSUE TITLE
Possibilidade de incluir atributo para "publicado online"

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/Web#511]
Consultando a JATS observamos que eles possuem um atributo para esse tipo de caso. Colocamos atributo "pub" e em homolog só aparece o dado, não aparecendo a informação de publicada online.
Abaixo atributos da JATS para date-type.
![sem titulo](https://cloud.githubusercontent.com/assets/19777809/16056991/3cd1924c-324e-11e6-9286-33d06f2a2c1c.png)

**Comment by robertatakenaka** [comment]
@lucasssantos : Por favor, indicar como está no XML (com os elementos e não somente o atributo) e como deveria ser apresentado no site.

**Comment by lucasssantos** [comment]
No xml está assim:

```<history>
				<date date-type="received">
					<day>26</day>
					<month>01</month>
					<year>2015</year>
				</date>
				<date date-type="received">
					<day>18</day>
					<month>07</month>
					<year>2015</year>
				</date>
				<date date-type="accepted">
					<day>24</day>
					<month>08</month>
					<year>2015</year>
				</date>
				<date date-type="accepted">
					<day>11</day>
					<month>03</month>
					<year>2016</year>
				</date>
			</history>```

Em homolog está: Recebido: 28 de Novembro de 2014; Revisado: 15 de Setembro de 2015; Aceito: 20 de Setembro de 2015; Aceito: 11 de Março de 2016

@robertatakenaka fiz o teste com o @alexxpsilva deixando o valor "pub" e aparece assim em homolog:

Recebido: 28 de Novembro de 2014; Revisado: 15 de Setembro de 2015; Aceito: 20 de Setembro de 2015; 11 de Março de 2016

**Comment by robertatakenaka** [comment]
@lucasssantos : por favor, verificar se está documentado no SPS está sugestão de usar pub.

**Comment by lucasssantos** [comment]
@robertatakenaka , no SPS não está documentada a utilização de 'pub', apenas 'received, 'rev-recd' e 'accepted'.

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.5-branch/tagset/elemento-history.html

Verifiquei que não indiquei como deveria ficar no site.

P. ex.: Recebido: 28 de Novembro de 2014; Revisado: 15 de Setembro de 2015; Aceito: 20 de Setembro de 2015; Publicado: 11 de Março de 2016

**Comment by alexxpsilva** [comment]
@robertatakenaka a Leticia disse que isso já está sendo previsto em outros tickets do SPS.
