### ISSUE TITLE
Apresentação de tabelas codificadas

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#514]
Em homolog a tabela está desconfigurada conforme abaixo

![ticket_tab](https://cloud.githubusercontent.com/assets/15328777/16280797/b669956a-3897-11e6-9e35-56932800c8f4.png)

Disponível através do link: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0080-21072016000200225&lng=en&nrm=iso&tlng=en

Já na versão Beta, aparece de forma correta

![ticket_tab-beta](https://cloud.githubusercontent.com/assets/15328777/16280875/193a1408-3898-11e6-9009-0a9d8b73f691.png)

Disponível através do link: http://homolog.xml.scielo.br/article_plus.php?pid=S0080-21072016000200225&tlng=en&lng=en

No Preview do Style Checker também aparece de forma correta.

**Comment by natalieakemi** [comment]
Estou tendo o mesmo problema de tabelas desconfiguradas em homolog.

No homolog:
![image](https://cloud.githubusercontent.com/assets/19558447/16380834/b88a1c8c-3c4f-11e6-98bb-0348838f3de2.png)
Disponível através do link: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0021-75572016000400046&lng=en&nrm=iso&tlng=pt
![image](https://cloud.githubusercontent.com/assets/19558447/16380911/1ed7e032-3c50-11e6-99bb-34d7b2e4136c.png)
Disponível através do link: http://homolog.xml.scielo.br/article_plus.php?pid=S0021-75572016000400046&tlng=pt&lng=en
