### ISSUE TITLE
Atributo "editor" não aparece como autor

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#515]
No SPS temos documentado o valor "editor" para contrib

http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib.html#contrib

Mas no sumário eletrônico do site não aparece como autores.

Exemplo:

![fasc 4](https://cloud.githubusercontent.com/assets/15328777/16466911/450f40e8-3e1b-11e6-8b4b-358ddc63f510.gif)

**Comment by robertatakenaka** [comment]
não foi possível simular o problema

**Comment by alexxpsilva** [comment]
@robertatakenaka não entendi o que quis dizer

**Comment by alexxpsilva** [comment]
@robertatakenaka peguei outro caso com o mesmo problema.

No XML.

```<contrib-group>
				<contrib contrib-type="editor">
					<name>
						<surname>Melo</surname>
						<given-names>Paulo</given-names>
					</name>
				</contrib>
			</contrib-group>
```
No sumário eletrônico não aparece:

Link do homolog: http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0102-053620160004&lng=en&nrm=iso

**Comment by robertatakenaka** [comment]
@alexxpsilva : apesar do autor ser um editor, o papel dele é de autor do texto.

**Comment by alexxpsilva** [comment]
@robertatakenaka entendi o que quis dizer, mas nesse caso acho que não se aplica.
Se fosse para colocar o cargo, colocaríamos na tag ```role```.
Abri o ticket porque nesse caso o próprio editor também é o autor do texto, e segundo o SPS http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib.html#contrib temos o atributo, ao meu ver deveria aparecer, por isso abri o ticket.

**Comment by robertatakenaka** [comment]
@alexxpsilva : cargo = role; tipo de contribuição = contrib-type. O Editor é editor do artigo ou autor do artigo?

**Comment by alexxpsilva** [comment]
neste caso, ele é editor da revista e autor do artigo também. Geralmente a grande maioria dos editoriais vem dessa forma.

**Comment by robertatakenaka** [comment]
@alexxpsilva : mporta que no artigo ele é o author. No sumário somente aparece quando o contrib-type é igual a author.

**Comment by alexxpsilva** [comment]
@robertatakenaka no caso o ticket também é para aparecer para todos esses atributos válidos na documentação.

**Comment by robertatakenaka** [comment]
@alexxpsilva : no sumário somente são apresentados os autores

**Comment by RPostalli** [comment]
@robertatakenaka você esta confundindo a função cargo e a função do autor. Na biblioteconomia, você pode ter autores que contribuem (contrib) de formas diferentes, como compilador, editor e etc que são (dentre as várias possibilidades que a JATS permite) os que documentamos em nosso SPS. Esta decisão já foi tomada em reuniões passadas do SPS e por isso precisamos que estes tipos a seguir, quando marcados no XML, aparecem em web (homologs e produção). Representam os tipos mais comuns e que aparecem no universo SciELO.

O atributo @contrib-type define o tipo de contribuição e pode ter os valores:

Valor	Descrição
author	Autor do conteúdo.
compiler	Compilador - Indivíduo que compilou o conteúdo a partir de várias fontes.
editor	Editor do conteúdo.
translator	Tradutor do conteúdo.

**Comment by RPostalli** [comment]
@robertatakenaka o contribuidor do tipo editor ainda é um autor, ele tem propriedade intelectual daquela obra, porque o sumário não reconhece a autoria do documento?

**Comment by robertatakenaka** [comment]
No site é apresentado no sumário somente quem está como "author", ou seja, se estiver como editor, translator, compiler, organizer, etc não aparece. Foi sempre assim.

**Comment by leticiaquino** [comment]
@robertatakenaka peguei a discussão somente agora, mas acredito que a @RPostalli tem razão.
Sempre tivemos arquivos com "autor-editor", por exemplo.

No site SciELO deveria aparecer a informação "Editor" (por exemplo), caso haja algum autor com o atributo ``@contrib-type="editor"``. 
Tenho para mim que isso estava funcionando há um tempo atrás. Alguma coisa mudou no site?
