### ISSUE TITLE
Duplicidade de PDF´s

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#526]
Na errata da RLAE está aparecendo vários PDF´s ao lado direito :  
![rlae_errata](https://cloud.githubusercontent.com/assets/16937218/16780091/79c5bf58-484b-11e6-9c16-78a3cef2ac0f.png)

Ao tentar abri-los aparece a seguinte mensagem: 
![sem titulo 2](https://cloud.githubusercontent.com/assets/16937218/16780110/912d51a6-484b-11e6-8c24-831d0eea7b7b.png)

Segue links:

homolog xml

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100900&lng=en&nrm=iso&tlng=en

homolog br

http://homolog.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100900&lng=en&nrm=iso&tlng=en

scielo br

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-11692016000100900&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
duplicated #522
