### ISSUE TITLE
Product de Artigos

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/Web#532]
A estrutura dentro da tag `<product>` tem que ter `<article-title>` também já que `<product>` permite a resenha de artigo. Também as informações de periodicidade: `<day>`, `<month>`, `<season>`, `<volume>`,  `<issue>` e `<fpage>` e `<lpage>` pois não está gerando de forma correta.
No xml:
![image](https://cloud.githubusercontent.com/assets/19558447/17058968/40c9ea5c-4ff9-11e6-9ebe-97a057f89137.png)

Em Homolog:
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47142005000300567&lng=en&nrm=iso&tlng=pt

![image](https://cloud.githubusercontent.com/assets/19558447/17058925/0887e752-4ff9-11e6-9441-a2b18706aed1.png)

**Comment by RPostalli** [comment]
Estrutura básica de pontuação para **book**.

autor(ponto). título do livro(ponto). edição(usa número ed ponto). cidade e/ou país(dois pontos): editora(vírgula), ano(ponto). página total(ponto).

EXEMPLO: 
GOMES, L. G. F. F. Novela e sociedade no Brasil. 6. ed. Niterói: EdUFF,
1998.

Estrutura básica de pontuação para **article**.

autor(ponto). título do artigo(ponto). nome da revista(vírgula), cidade e/ou país(vírgula), volume(usa v ponto número vírgula), número(usa n ponto número vírgula), intervalo de página (número hifén número vírgula), mês(por extenso ponto). ano(ponto).

EXEMPLO: 
GURGEL, C. Reforma do Estado e segurança pública. Política e
Administração, Rio de Janeiro, v. 3, n. 2, p. 15-21, set. 1997.

Mais dados que surgirem além deses pode ser adotado vírgula ,

**Comment by javani** [comment]
@robertatakenaka em algum momento decidiu-se que a pontuação em ```[<product>](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-product.html)``` seria mantida e está apresentando pontuações a mais por conta da css aplicada. Veja o exemplo:
![image](https://user-images.githubusercontent.com/912953/33140384-f988d68e-cf96-11e7-8fc1-ec8fa9d2f9a4.png)

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0102-311X2017000908001&lng=en&nrm=iso

Marcação:

```xml
<product product-type="book">
	<person-group person-group-type="compiler">
		<name>
			<surname>Carrara</surname>
			<given-names>S</given-names>
		</name>
		<name>
			<surname>Carvalho</surname>
			<given-names>M</given-names>
		</name>
</person-group><bold>, organizadores.</bold><publisher-loc>Rio de Janeiro</publisher-loc><bold>:</bold><publisher-name>Editora Fiocruz</publisher-name><bold>;</bold><year>2016</year><bold>.</bold><size units="pages">234</size><bold>.</bold><isbn>978-85-7541-473-6</isbn>
</product>
```

**Comment by robertatakenaka** [comment]
@javani : o problema neste caso é que as pontuações estão dentro de um elemento (bold), assim a XSL entende que não há pontuação "solta" e por isso há as pontuações a mais.
Sugiro então remover os `<bold>`

**Comment by javani** [comment]
@robertatakenaka era isso mesmo. Vou abrir um ticket para incluir essa informação na documentação de preparação de artigos para marcação.
