### ISSUE TITLE
Resumo

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/Web#537]
O resumo em francês não está aparecendo corretamente em homolog.xml

![image](https://cloud.githubusercontent.com/assets/19558447/17527014/13cd8874-5e40-11e6-900b-bbc87c16c34c.png)
http://homolog.xml.scielo.br/scielo.php?script=sci_abstract&pid=S1415-47142000000400059&lng=en&nrm=iso&tlng=fr

Na parte do texto o resumo aparece completo:
![image](https://cloud.githubusercontent.com/assets/19558447/17527147/8a4fa98c-5e40-11e6-9254-6ca3001c7f35.png)

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1415-47142000000400059&lng=en&nrm=iso&tlng=pt

Marcação no xml:
![image](https://cloud.githubusercontent.com/assets/19558447/17527061/3ebfab98-5e40-11e6-875f-5fae26c23875.png)

**Comment by robertatakenaka** [comment]
@natalieakemi , @RPostalli: devido a limitação da base que não permite registro muito grande para armazenar todos os resumos, dependendo da quantidade de resumos e/ou seu tamanho, alguns deles são cortados da base, no entanto, são apresentados no texto completo.

**Comment by RPostalli** [comment]
@robertatakenaka qual o limite de palavras para aparecer no resumo?
