### ISSUE TITLE
Tag Attrib em figuras

### ISSUE THREAD

**Issue by lucasssantos** [scieloorg/Web#541]
No homolog.xml quando há duas tags de `<attrib> dentro de`<fig```o dado não separa, conforme exemplo abaixo:

![sem titulo](https://cloud.githubusercontent.com/assets/19777809/17735126/04d2704c-6457-11e6-92a0-93e343b84c3a.png)

O .xml está dessa forma:

![semwtitulo](https://cloud.githubusercontent.com/assets/19777809/17735155/2a39ef72-6457-11e6-943a-1a3d80df3066.png)

Link do relatório: http://homolog.xml.scielo.br/reports/jpe/v27/xml_converter.html
Link para o homolog: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S2448-24552016000100112&lng=en&nrm=iso&tlng=en#f2

**Comment by natalieakemi** [comment]
O mesmo problema ocorre com o a Revista CEFAC no homolog.xml e no site final.

![image](https://cloud.githubusercontent.com/assets/19558447/18255680/493367e8-7382-11e6-8632-1610bcaf88d1.png)

No xml:
![image](https://cloud.githubusercontent.com/assets/19558447/18255704/8735cbbc-7382-11e6-9a47-ea5bbc182231.png)

Link do site: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1516-18462016000400854&lng=pt&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
@lucasssantos , @natalieakemi , @RPostalli, @leticiaquino: 
1) attrib deve conter apenas a fonte ou autoria da figura
2) a legenda referente à figura deveria ter um elemento próprio ou fazer parte da imagem

Por ora, posso ajustar a apresentação, no entanto, a identificação dos dados está incorreta.

**Comment by RPostalli** [comment]
@robertatakenaka marcar dados "buscáveis" como imagem não vem ao encontro do que o Abel esta buscando uma vez que agora passa a ser obrigatório codificação de tabelas e equações.

Independente do que esteja marcado dentro de atrib (isso esta relacionado ao bom senso de quem esta marcando), é possível que uma figura ou tabela possua dois "atribs" e a diagramação na nossa interface tem que ficar correta, com uma abaixo da outra.

Consulte na JATS sobre a tag http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-d6c0.html

Veja que ele não serve apenas para: " 2. attrib deve conter apenas a fonte ou autoria da figura"

Usage: This element is a **very unregulated container** that may hold a description of the source, name of the author, **formal thanks, copyright material, or other information**.

Por favor ajustar a apresentação.
