### ISSUE TITLE
"Texto completo disponível apenas em PDF"

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#542]
O link "Texto completo disponível apenas em PDF" está duplicando quando o artigo é em outra língua que não seja Português, Inglês ou Espanhol.

Links em homolog.xml: 

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S2237-26602014000300425&lng=en&nrm=iso&tlng=pt

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S2237-26602014000300486&lng=en&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
@jenniferamato me parece que está corrigido
