### ISSUE TITLE
Author-notes

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#543]
Quando o arquivo possui sub-article com author-notes e no article não, ele está assumindo o author-notes do sub-article para as duas línguas. 

Exemplo:  
2237-2660-rbep-4-03-00509.xml
X:\fbpe\periodicos\rbep\v4n3\2237-2660-rbep-4-03_xml_package_maker_result\2237-2660-rbep-4-03

**Comment by robertatakenaka** [comment]
@jenniferamato : por favor, indicar o artigo no site.

**Comment by jenniferamato** [comment]
@robertatakenaka , na época foi realizada a correção pois o article possuía author-notes também mas não tinha sido marcado. Quer que simule algum caso semelhante em homolog?
