### ISSUE TITLE
Fn-group

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#545]
Quando o artigo corrigido pela errata possui sub-article mas a correção é realizada em apenas uma das línguas, o fn-group aparece nas duas. 

No xml a nota está apenas em uma das línguas, mas em homolog aparece nas duas. 

Problema parecido com o do ticket  #543 referente a author-notes. 

Exemplo em homolog.xml:

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1983-14472016000200501&lng=en&nrm=iso&tlng=en

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1983-14472016000200501&lng=en&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
@jenniferamato : por favor, confirme se entendi bem:
a nota de rodapé está no article e não no sub-article, então ela deve aparecer somente no article e não no sub-article.
