### ISSUE TITLE
[HOMOLOG] Link não está funcionando entre autor e nota de autor 

### ISSUE THREAD

**Issue by suelylc** [scieloorg/Web#546]
Se o `fn` estiver dentro de `<author-notes>` o `<xref ref-type="fn" rid="fn1">` não está fazendo link

![bug_fn_homolog](https://cloud.githubusercontent.com/assets/6921625/18127474/fb8ced4a-6f56-11e6-87d2-7d066b66e6ef.png)

Artigo no homolog:

http://homolog.scielo.br/scielo.php?script=sci_arttext&pid=S0100-879X2016001000604&lng=en&nrm=iso&tlng=en#back_fn1

**Comment by RPostalli** [comment]
Suely neste caso não seria porque o asterisco está em sup? o asterisco devia ser presento por um label. Não?

**Comment by suelylc** [comment]
@RPostalli  A referencia cruzada ocorre entre rid e id

**Comment by RPostalli** [comment]
Eu sei, mas o asterisco é um label, não um sup, o mesmo label que esta em xref. Vc testou? Coloca o label e veja se funciona.

**Comment by suelylc** [comment]
Sim, @RPostalli testei. Não funciona.
