### ISSUE TITLE
[homolog] ORCID

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#547]
Em Homolog o ORCID aparece colocado com o nome do autor

![homolog_orcid](https://cloud.githubusercontent.com/assets/15328777/18142464/04a6a668-6f94-11e6-9b7a-d4de03ca23ce.png)

Link do homolog: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0034-73292016000200205&lng=en&nrm=iso&tlng=en

Marcação no XML

![xml_orcid](https://cloud.githubusercontent.com/assets/15328777/18142552/8915af5c-6f94-11e6-8884-6e502c81e971.png)

O ideial seria aparecer abaixo do nome do autor, seguido da informação "ORCID: 00000000000"

Não somente com o ORCID mas para todos os valores segundo a documentação http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.4-branch/tagset/elemento-contrib-id.html#contrib-id

**Comment by RPostalli** [comment]
EMAIL
de:	Letra1 - Serviços Editoriais <letra1@editoraletra1.com> por  scielo.org 
responder a:	letra1@editoraletra1.com.br
para:	Produção Bibliotecárias <producao@scielo.org>
data:	24 de outubro de 2016 08:45
assunto:	formatação no HTML

Bom dia!

Verificando o artigo http://dx.doi.org/10.1590/2358-2936e2016017 
notei que há um erro de formatação no Html, tendo o Orcid ficado sobreposto ao nome do autor:
Imagem inline 1

Poderiam verificar, por favor.

Grato.
Ronaldo Machado

**Comment by alexxpsilva** [comment]
@RPostalli no caso desse artigo está com a informação "http://orcid.org/" e foi documentado que não é necessário conforme exemplo disponível em http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-contrib-id.html.

Mas pe necessário corrigir a questão do dado ficar "grudado" ao nome do autor".

**Comment by robertatakenaka** [comment]
@RPostalli @alexxpsilva : Vai ficar assim. No site novo vai ficar melhor.
![captura de tela 2016-10-24 as 11 00 43](https://cloud.githubusercontent.com/assets/505143/19646814/f62472a8-99d9-11e6-8f30-2a5b956791c4.png)

**Comment by alexxpsilva** [comment]
@robertatakenaka assim está bem melhor

**Comment by RPostalli** [comment]
Vai repetir o nome do autor? Acho redundante, não gostei, fica poluído.

Não acho legal aparecer o http, o número deve ser um hiperlink, mas sem aparecer o http://orcid.org/, pois documentamos que o dado a ser inserido É APENAS O NÚMERO ORCID.

Na visualização (na minha opinião) ficaria melhor inserir entre parenteses ao lado do nome do autor exemplo:

Giuseppe Montesanto 1 (Orcid: 0000-0001-8946-1185), Fulano da Silva 2 (Orcid: 0000-0001-8946-1184)

**Comment by robertatakenaka** [comment]
@alexxpsilva e @RPostalli : por gentileza, para as próximas solicitações, já indiquem a forma que querem que apareça no site para evitar retrabalho. Vou fazer o que a renata sugeriu.

**Comment by RPostalli** [comment]
Roberta, normalmente a gente não informa "o como fazer" porque não sabemos quais as implicações técnicas da interface.  Por isso decidimos juntos com você que é a especialista guiando a criação OK.

**Comment by robertatakenaka** [comment]
@RPostalli pode ficar assim então?

**Comment by RPostalli** [comment]
@robertatakenaka vc diz desta forma? https://cloud.githubusercontent.com/assets/505143/19647429/c36d87f2-99dc-11e6-9594-392e70d3cee3.png

Se sim, pode. ficou ótimo.

**Comment by leticiaquino** [comment]
@robertatakenaka gostaria de reabrir o ticket para sugerir uma alteração na apresentação dessa informação.

Por favor, verificar a possibilidade de colocar a informação de ORCID com aparencia de link e em uma fonte menor que a do autor.
Dessa forma não ficará confuso.

**Comment by suelylc** [comment]
@robertatakenaka  é possível aplicar essa forma de apresentação de ORCID no BR em SciELO SP? 

Atualmente está assim: 
http://homolog.xml.scielosp.org/scielo.php?script=sci_arttext&pid=S1851-82652016000200149&lng=en&nrm=iso&tlng=es

e no BR está assim: 
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0104-64972016000100802&lng=en&nrm=iso&tlng=en

**Comment by javani** [comment]
@robertatakenaka Segue link de referência para apresentação de ORCID para web.

http://orcid.org/trademark-and-id-display-guidelines

**Comment by robertatakenaka** [comment]
@javani, @RPostalli : Vejam como ficou considerando as recomendações acima mencionadas.
<img width="533" alt="captura de tela 2017-01-02 as 13 32 07" src="https://cloud.githubusercontent.com/assets/505143/21591943/1d8809f2-d0f0-11e6-92c3-5063b535ff41.png">
<img width="494" alt="captura de tela 2017-01-02 as 13 29 12" src="https://cloud.githubusercontent.com/assets/505143/21591944/1fd96796-d0f0-11e6-86e3-9813f1f7c3aa.png">

**Comment by RPostalli** [comment]
Roberta, mantenha como já estava e acrescente apenas o logo.

Giuseppe Montesanto 1 (Orcid: 0000-0001-8946-1185), Fulano da Silva 2
(Orcid: 0000-0001-8946-1184)

Já tínhamos combinado de não aparecer o link http e o número do orcid ser
linkável.

Tem que aplicar em SciELO SP também.

Obrigada.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão XPM 11/04/2016, será descontinuada em 9 de janeiro de
2017. Por gentileza, passem a usar a versão com relatório 21/11/2016
<http://docs.scielo.org/projects/scielo-pc-programs/en/latest/download.html>
]

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

2017-01-02 13:34 GMT-02:00 Roberta Takenaka <notifications@github.com>:

**Comment by javani** [comment]
Boa tarde meninas,

Renata,

Estamos incluindo conforme padrão indicado pelo ORCID.
Veja: http://orcid.org/trademark-and-id-display-guidelines

Acho que o melhor é apresentarmos como eles sugerem.

http://orcid.org/0000-0002-1825-0097

Grata,

 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=javani.araujo@scielo.org&idSignature=22>

Javani Araujo
*SciELO Brasil*
*FAPESP - CNPq - BIREME - **FAP UNIFESP*
*Av. Onze de Junho, 269*
*04041-050 - São Paulo-SP - Brasil*
*Tel.: 55-11-5083-3639*
*www.scielo.org <http://www.scielo.org/> | www.scielo.br
<http://www.scielo.br/> | blog.scielo.org <http://blog.scielo.org/>*

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

Em 2 de janeiro de 2017 13:40, Renata Postalli <notifications@github.com>
escreveu:

**Comment by RPostalli** [comment]
Ok Java.

Eu acho poluído, mas por mim sem problemas.

Atenciosamente,

Renata Postalli
Bibliotecária Júnior

---------------
[Atenção: A versão XPM 11/04/2016, será descontinuada em 9 de janeiro de
2017. Por gentileza, passem a usar a versão com relatório 21/11/2016
<http://docs.scielo.org/projects/scielo-pc-programs/en/latest/download.html>
]

[Atenção: A versão 1.3 do SciELO PS, foi descontinuada em 5 de outubro de
2016. Por gentileza, passem a utilizar a versão 1.4 ou 1.5 do SPS
<http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/>.]

SciELO - Scientific Electronic Library Online
FAPESP - CNPq - BIREME - FAP UNIFESP
www.scielo.org | www.scielo.br
______________________________
Avenida Onze de Junho, 269
04041-050 - São Paulo-SP - Brasil
Tel.: 55-11-5083-3639

Em 2 de janeiro de 2017 13:45, javani <notifications@github.com> escreveu:

**Comment by lpanebr** [comment]
Apenas um detalhe, mas a recomendação é utilizar `https`.
