### ISSUE TITLE
 link [Home] no rodapé da Pagina /RBRH

### ISSUE THREAD

**Issue by Aleciom** [scieloorg/Web#551]
O link [Home] no rodapé da pagina (http://www.scielo.br/revistas/rbrh/iaboutj.htm) está apontando para outra revista. http://www.scielo.br/scielo.php?script=sci_serial&lng=en&pid=1517-9702&nrm=iso

![sem titulo](https://cloud.githubusercontent.com/assets/15981383/18207573/0f80236a-7102-11e6-887a-c2a067dd4ff2.jpg)

**Comment by robertatakenaka** [comment]
@Aleciom / @RPostalli: esta página não faz parte da aplicação Web. A equipe de conversão pode fazer a correção.

**Comment by RPostalli** [comment]
Encaminhado para a equipe responsável (conversão) para avaliar o caso.

**Comment by RPostalli** [comment]
Problema resolvido. Msg de Felipe:

Renata, 

O link informado está atualizado: http://www.scielo.br/revistas/rbrh/iaboutj.htm
