### ISSUE TITLE
Link para errata não é apresentado conforme esperado no site final

### ISSUE THREAD

**Issue by leticiaquino** [scieloorg/Web#553]
No site final a informação de errata é apresentada sem o formato esperado, apenas como um link. Veja:

![errata-site-final](https://cloud.githubusercontent.com/assets/4397365/18631430/5186fb96-7e48-11e6-9272-8215fa9434ad.jpg)

Porém no [homolog.scielosp.org](http://homolog.scielosp.org/scielo.php?script=sci_arttext&pid=S1726-46342016000200385&lng=en&nrm=iso&tlng=es) e em [homolog.xml.scielosp.org](http://homolog.xml.scielosp.org/scielo.php?script=sci_arttext&pid=S1726-46342016000200385&lng=en&nrm=iso&tlng=es) a errata é apresentada com o estilo esperado. Veja:

**Homolog.xml.scielosp:**
![errata - homolog-xml](https://cloud.githubusercontent.com/assets/4397365/18631788/6a9d1730-7e4a-11e6-8ed5-9d431ab022e2.jpg)

**Homolog.scielosp:**
![errata-homolog](https://cloud.githubusercontent.com/assets/4397365/18631794/762ad862-7e4a-11e6-87b3-79c5baadecaf.jpg)

Por favor, considerar no site final a informação de errata com o formato apresentado em homolog.

**Comment by alexxpsilva** [comment]
Apenas complementando...

Quando a errata corrige um artigo em HTML é gerado a caixa amarela corretamente.
Exemplo: http://homolog.scielo.br/scielo.php?script=sci_arttext&pid=S0034-71672016000501002&lng=en&nrm=iso&tlng=en

Mas em produção é gerado a caixa amarela sem informação.
Exemplo: http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0034-71672016000501002&lng=en&nrm=iso&tlng=en

O correto seria aparecer igual em homolog.

**Comment by robertatakenaka** [comment]
Corrigido com a atualização da aplicação do site (chamado infra  788)
