### ISSUE TITLE
<attrib> não aparece em homolog.xml

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/Web#559]
Quando identificado dentro de `table-wrap` a tag `atrib` não aparece no homolog.xml.

![image](https://cloud.githubusercontent.com/assets/19558447/19966586/89b6fc8a-a1b3-11e6-81de-e35f2c43a2b3.png)

![image](https://cloud.githubusercontent.com/assets/19558447/19966589/8e2a7454-a1b3-11e6-9f75-b8ac9b894f3e.png)

**Comment by RPostalli** [comment]
Roberta, a JATS permite attrib tanto em table-wrap quanto em table-wrap-foot. Em web tem que aparecer para os dois casos

***O fato no site não estar reconhecendo em table-wrap, esta fazendo com que os técnicos tenham que realizar a correção manual tabela por tabela, uma vez que no SPS está faltando esta informação e ainda não corrigiram (ver ticket https://github.com/scieloorg/scielo_publishing_schema/issues/480)

**Comment by leticiaquino** [comment]
Relacionado ao ticket: https://github.com/scieloorg/scielo_publishing_schema/issues/480
