### ISSUE TITLE
No homolog.xml não aparece a seção

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/Web#562]
A seção não aparece em homolog xml, conforme os links abaixo:

Exemplo 1: Revista FM - Seção "Editorial"
http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0103-515020160004&lng=en&nrm=iso
Está assim no XML:
![image](https://cloud.githubusercontent.com/assets/19558447/20401199/f22b2f8a-acde-11e6-802d-ca3fe8f07a30.png)

Exemplo 2: Revista AABC - Seção "Biological Sciences"
http://homolog.xml.scielo.br/scielo.php?script=sci_issuetoc&pid=0001-376520160005&lng=en&nrm=iso
Está assim no XML:
![image](https://cloud.githubusercontent.com/assets/19558447/20401294/5a60222c-acdf-11e6-9f30-ea07673a7206.png)

Já verifiquei a title e ambos cadastros de seção estão corretos.

**Comment by robertatakenaka** [comment]
problema era relacionado à geração da base (https://github.com/scieloorg/PC-Programs/issues/2429)
