### ISSUE TITLE
Apresentação de imagens em SVG 

### ISSUE THREAD

**Issue by javani** [scieloorg/Web#586]
@fabiobatalha 
As imagens em SVG, ainda que disponíveis e endereçadas corretamente no XML, não são apresentadas nos artigos.

No artigo
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0034-89102017000100202&lng=en&nrm=iso&tlng=en
![image](https://cloud.githubusercontent.com/assets/912953/21727035/70afa5d4-d426-11e6-8892-25e243ba9e79.png)

No link da imagem:
http://homolog.xml.scielo.br/img/revistas/rsp/v51//0034-8910-rsp-S1518-87872017051006523-e1.svg
![image](https://cloud.githubusercontent.com/assets/912953/21727060/8c492810-d426-11e6-8b7e-7a8b5000944a.png)

Pedimos especial atenção na resolução do problema, uma vez que não teremos como processar os números até que a visualização na página do artigo seja possível.

**Comment by fabiobatalha** [comment]
corrigido.

**Comment by javani** [comment]
@fabiobatalha a visualização do SVG foi resolvido no elemento dis-formula. Ele também deve aparecer em table-wrap. Poderia verificar e fazer o ajuste?

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1516-35982016001200737&lng=en&nrm=iso

http://homolog.xml.scielo.br/img/revistas/rbz/v45n12//1516-3598-rbz-45-12-00737-gt1.svg

Grata,

**Comment by javani** [comment]
@fabiobatalha precisa ajustar também para inline-graphic

**Comment by fabiobatalha** [comment]
@javani 

As correções foram implementadas em homolog.xml.scielo.br

Verificar se estão ok.

**Comment by javani** [comment]
@fabiobatalha por favor, aplicar a alteração em SciELO SP (homolog e produção)

**Comment by fabiobatalha** [comment]
@javani produção tbém? Quer dizer que funcionou bem?

**Comment by javani** [comment]
@fabiobatalha aparentemente está melhor do que estava, mas ainda necessitamos entender mais para solicitar melhor os ajustes. No momento podemos pedir correção nos arquivos onde as imagens png ou outros formatos forma imbutidas no SVG. Você poderia atualizar homolog e produção, pf?

**Comment by javani** [comment]
@fabiobatalha por favor, ajustar as páginas homolog.scielo.br e www.scielo.br para visualização das imgs em SVG.
http://homolog.scielo.br/scielo.php?script=sci_arttext&pid=S1519-70772017000100011&lng=en&nrm=iso&tlng=en

**Comment by javani** [comment]
@fabiobatalha por favor, ajustar as páginas homolog.xml.scielosp.org, esqueci de pedir. Grata

**Comment by robertatakenaka** [comment]
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1516-31802017005002101&lng=en&nrm=iso&tlng=en

```xml
<table-wrap id="t1">
                                        <label>Table 1:</label>
                                        <caption>
                                                <title>Database search results for acute promyelocytic leukemia, FLT3-ITD and WT1 on August 5, 2016</title>
                                        </caption>
                                        <graphic xlink:href="1806-9460-spmj-1516-3180-2016-020104102016-gt1.svg"/>
                                </table-wrap>
```

**Comment by robertatakenaka** [comment]
Segundo javani, o problema é na imagem, não o site.
