### ISSUE TITLE
texto Disponível apenas em PDF" sem link (revenf)

### ISSUE THREAD

**Issue by Gabrielacrah** [scieloorg/Web#601]
No homolog (revenf), o link em: "Texto disponível apenas em PDF" não está funcionando.

Exemplo do artigo:
HOMOLOG (revenf):
http://homolog.xml.revenf.bvs.br/scielo.php?script=sci_arttext&pid=S0080-62341991000300259&lng=pt&nrm=iso&tlng=pt

Exemplo do PDF
http://homolog.xml.revenf.bvs.br/pdf/reeusp/v25n3/0080-6234-reeusp-25-3-259.pdf

Esse erro está acontecendo em todos os fascículos retrospectivos de RevEnf.

**Comment by robertatakenaka** [comment]
duplicated #600
