### ISSUE TITLE
Não é possível visualizar o vídeo em homolog.xml

### ISSUE THREAD

**Issue by natalieakemi** [scieloorg/Web#618]
O vídeo marcado em XML não está aparecendo no site de homolog.xml, conforme o link abaixo:
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0365-05962017000300413&lng=en&nrm=iso&tlng=en

A marcação está de acordo com a [documentação](http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/1.6-branch/tagset/elemento-media.html#media):
`<`media xlink:href="0365-0596-abd-92-03-0413-m01.avi" mimetype="video"
                    mime-subtype="avi"/`>`

O vídeo está dentro do pacote com a nomeação correta.

O pacote com os arquivos está salvos em: **V:\SciELO\serial\abd\v92n3\0365-0596-abd-92-03**

**Comment by natalieakemi** [comment]
Apenas complementando o vídeo também não está subindo em http://homolog.scielo.br e nem no site final, conforme os links abaixo:

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0365-05962017000300413&lng=en&nrm=iso&tlng=en

http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0365-05962017000300413&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@natalieakemi @RPostalli

Os vídeos tem que ser no formato mp4 para ser reconhecido por todos os browsers.

> AVI (Audio Video Interleave). Developed by Microsoft. Commonly used in video cameras and TV hardware. Plays well on Windows computers, but not in web browsers.
https://www.w3schools.com/html/html_media.asp

**Comment by RPostalli** [comment]
@robertatakenaka nos nunca documentamos o formato obrigatório para videos, tanto que no exemplo http://docs.scielo.org/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-media.html#exemplo-de-media-em-elemento-fig o formato é o avi. Desde quando esta decisão foi tomada, isso foi discutido no grupo do SPS? Precisamos documentar urgente isso no Guia e informar os técnicos.

**Comment by robertatakenaka** [comment]
@RPostalli: Não tem a ver em nada com SPS. Não é uma questão de decisão. É uma questão de tecnologia. Nenhum browser toca .avi. Leia meu comentário anterior.

**Comment by RPostalli** [comment]
@robertatakenaka obrigada por informar qual a versão atual multiplataforma de vídeo. Tomarei as devidas providências para correção do pacote e da documentação.

**Comment by robertatakenaka** [comment]
@RPostalli : nesta mesma página há informação sobre audio. Vale a pena revisar se há erro no SPS referente a audio.
