### ISSUE TITLE
Equações não aparecem corretamente em homolog.xml.revtur.org

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#623]
As equações não estão sendo apresentadas corretamente em homolog.xml.revtur.org. 

![revtur](https://user-images.githubusercontent.com/16937218/29042797-d24d7036-7b8e-11e7-94ab-5a7693d3769a.png)

Após clicar em "Carregar scripts não seguros" as equações aparecem corretamente: 

![revtur2](https://user-images.githubusercontent.com/16937218/29042803-d7225914-7b8e-11e7-9456-ee9d4d8e358f.png)

![revtur3](https://user-images.githubusercontent.com/16937218/29042854-1b101b7a-7b8f-11e7-893d-9eab3afe84b9.png)

O teste foi realizado em diferentes navegadores.

Link em homolog.xml: 

https://homolog.xml.revtur.org/scielo.php?script=sci_arttext&pid=S1984-48672016000300474&lng=en&nrm=iso&tlng=pt

**Comment by robertatakenaka** [comment]
@jenniferamato : Houve uma mudança no MathJax

https://www.mathjax.org/cdn-shutting-down/


For example, if you have been using the latest MathJax version (v2.7.0) change

<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/2.7-latest/MathJax.js?...">
</script>

to

<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?...">
</script>
