### ISSUE TITLE
[Homolog] Equação codificada não aparece quando dentro de <fig>

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/Web#635]
No arquivo em anexo há uma equação codificada dentro de <`fig`> que não está aparecendo em homolog.

[1808-2386-bbr-14-06-0592.zip](https://github.com/scieloorg/Web/files/1514496/1808-2386-bbr-14-06-0592.zip)

Relatório XC: http://homolog.xml.scielo.br/reports/bbr/v14n6/xc_2017-11-28_100705.html
Link para o artigo: http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1808-23862017000600592&lng=en&nrm=iso&tlng=en

**Comment by robertatakenaka** [comment]
@JoyceRaphaela : vou verificar, mas não existe conteúdo fig codificado... O que existe é disp-formula ou inline-formula. Será que não é este o problema?

**Comment by robertatakenaka** [comment]
<img width="814" alt="captura de tela 2017-11-30 as 09 04 08" src="https://user-images.githubusercontent.com/505143/33427715-735eaf4e-d5ad-11e7-8bf8-5e92374aa454.png">
