### ISSUE TITLE
[Homolog] Tag <product> apresentando de forma não usual

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#651]
Observei que as resenhas no homolog estão apresentando a tag de product com a caixa de texto muito grande conforme imagem abaixo.

![homolog_product](https://user-images.githubusercontent.com/15328777/37048460-ba223eb0-214c-11e8-989c-96d916b1cce0.png)

**Comment by robertatakenaka** [comment]
Como está o XML?

**Comment by alexxpsilva** [comment]
```
<product product-type="book">
				<person-group person-group-type="author">
					<name>
						<surname>NOGUERA-RAMÍREZ</surname>
						<given-names>Carlos</given-names>
					</name>
				</person-group>. <source><italic>El gobierno pedagógico</italic>: del arte de educar
					a las tradiciones pedagógicas</source>. <publisher-loc>Bogotá</publisher-loc>:
					<publisher-name>Siglo del Hombre Editores</publisher-name>, <year>2012</year>
			</product>
```

**Comment by robertatakenaka** [comment]
@alexxpsilva : preciso do link da página também

**Comment by robertatakenaka** [comment]
@alexxpsilva : acho que sei o que aconteceu.
Estava fazendo um teste com SciELO 20 anos e durante os testes verifiquei que ao incluir a divulgação o HTML da página ficou com 2 html na mesma página, o que deve ter causado a apresentação incorreta do "product".
A correção foi feita fazem alguns minutos.
