### ISSUE TITLE
homolog.xml tpsy e civitas

### ISSUE THREAD

**Issue by odiliohilariomoreirajunior** [scieloorg/Web#653]
Ao tentar entrar no homolog.xml dos periódicos TPSY e CIVITAS através dos endereços http://homolog.xml.scielo.br/tpsy e http://homolog.xml.scielo.br/civitas somos direcionados automaticamente para o homolog.scielo.br.

**Comment by robertatakenaka** [comment]
@odiliohilariomoreirajunior : 
Os atalhos para as páginas iniciais das revistas não fazem parte da aplicação do site. Estes atalhos são configurados dentro dos servidores que hospedam o site.
Os atalhos só devem ser verificados no site de produção e no de homologação. No entanto, esta configuração é independente, ou seja, pode estar funcionando na homologação mas não na produção e vice-versa. Para esta questão usar o suporte.scielo.org.
Este ticket é inválido.
