### ISSUE TITLE
Incluir RBPV na lista de periódicos que apresentam badge do scimago

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/Web#661]
O código do periódico no scimago é `4500151538`, e o ISSN é `1984-2961`.

Aparentemente, basta incluir um novo elemento no arquivo `Web/htdocs/scimago/scimago.xml`

**Comment by gustavofonseca** [comment]
Curiosamente o item já está na lista, porém com referência ao ISSN impresso do periódico enquanto o site faz uso do eletrônico na geração do ID.

https://github.com/scieloorg/Web/blob/a1ab2b5375b7361a327a0b51f358da5d49fcf9f0/htdocs/scimago/scimago.xml#L630

**Comment by robertatakenaka** [comment]
Na apresentação se usa o ISSN_ID, ou seja, não depende se é o online ou o impresso, mas sim o ISSN registrado com ID (parte do PID).

<img width="742" alt="captura de tela 2018-07-04 as 15 59 24" src="https://user-images.githubusercontent.com/505143/42291638-53d6fa46-7fa3-11e8-8478-61421d34713f.png">

**Comment by robertatakenaka** [comment]
scimago.xml é gerado por um processo que deve estar em cron:

https://github.com/scieloorg/Web/blob/55d3031ab40be33e6efbfafcdb8917d40e113229/proc/scielo_sjr/shs/sjr_run.sh

Que executa:
```wget --output-document=temp.txt 'http://www.scimagojr.com/journalsearch.php?q='$2'&tip=iss&clean=0'```
No lugar do parametro ```$2```, valor dos campos v400 (ISSN_ID) e v935 (ISSN eletrônico)

https://github.com/scieloorg/Web/blob/55d3031ab40be33e6efbfafcdb8917d40e113229/proc/scielo_sjr/formats/sjr_format.pft
```
'./sjr_proc.sh ',v400,' ',v400#
'./sjr_proc.sh ',v400,' ',v935#
```
No caso desta revista, v400 é igual a 1984-2961 e o v935 também é 1984-2961.

Executando duas vezes:
https://www.scimagojr.com/journalsearch.php?q=1984-2961&tip=iss&clean=0

Resultando:
_Sorry, no results were found._

Sendo assim, a sugestão de correção é alterar o conteúdo de 
proc/scielo_sjr/formats/sjr_format.pft
De:
```
'./sjr_proc.sh ',v400,' ',v400#
'./sjr_proc.sh ',v400,' ',v935#
```
Para:
```
'./sjr_proc.sh ',v400,' ',v400#
,(if v435^*<>v400[1] then './sjr_proc.sh ',v400[1],' ',v435^*# fi),
```
O campo v435 é repetitivo e contempla os dois tipos de ISSN:
```
435  "0103-846X^tPRINT"
435  "1984-2961^tONLIN"
```

**Comment by gustavofonseca** [comment]
@robertatakenaka, uma dúvida: sendo o scimago.xml gerado automaticamente por meio do script mencionado em comentários anteriores, você acha correto ele estar versionado? Eu penso que não, que deveriam ser gerados e mantidos apenas nas instâncias.
