### ISSUE TITLE
Incluir BJFT na lista de periódicos que apresentam badge do Scimago

### ISSUE THREAD

**Issue by francine-curivil** [scieloorg/Web#663]
O ISSN é 1981-6723 e a URL no Scimago é https://www.scimagojr.com/journalsearch.php?q=21100432467&tip=sid&clean=0.

**Comment by robertatakenaka** [comment]
solução relacionada com #661

**Comment by robertatakenaka** [comment]
http://www.scielo.br/scielo.php?script=sci_serial&pid=1981-6723&lng=pt&nrm=iso
Resolvido com #669
