### ISSUE TITLE
Incluir EAN na lista de periódicos que apresentam badge do Scimago

### ISSUE THREAD

**Issue by jenniferamato** [scieloorg/Web#665]
O ISSN é 1414-8145 e a URL no Scimago é https://www.scimagojr.com/journalsearch.php?q=21100853577&tip=sid&clean=0

**Comment by robertatakenaka** [comment]
http://www.scielo.br/scielo.php?script=sci_serial&pid=1414-8145&lng=pt&nrm=iso
Resolvido com #669
