### ISSUE TITLE
Widget do Scimago não está sendo exibido os títulos recém-indexados

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/Web#666]
Segue lista dos títulos recém indexados, nas diversas coleções:

* Analisis Filosofico - AR
* Cinta de Moebio - CL
* Comunicacao e Sociedade - PT
* Cuadernos de historia (Santiago, Chile) - CL
* Manuscrito - BR
* Old Testament Essays - ZA
* Open Insight - MX
* Papers in Physics - AR
* Research on Biomedical Engineering - BR
* Revista Brasileira de Linguistica   Aplicada - BR
* Revista Chilena de Derecho y Tecnologia - CL
* Revista Finanzas y Politica Economica - CO
* Revista Luna Azul - CO
* Sociologia e Antropologia - BR

É importante notar que tratam-se de títulos indexados recentemente, o que me leva a inferir que além das correções do #664, a execução do shell script https://github.com/scieloorg/Web/blob/55d3031ab40be33e6efbfafcdb8917d40e113229/proc/scielo_sjr/shs/sjr_run.sh não esteja acontecendo com a devida frequência.

Relacionado com #661, #663 e #665

**Comment by robertatakenaka** [comment]
@gustavofonseca : o script roda por coleção.
Cada coleção sem ter o script para ter o link do scimago é necessário:
1. ter a aplicação do site atualizado
2. ter o script rodando com frequência ou editar manualmente o xml: htdocs/scimago/scimago.xml de acordo com o formato:
```xml
<?xml version='1.0' encoding='utf-8'?>
<SCIMAGOLIST>
    <title ISSN="1414753X" SCIMAGO_ID="5600155441"/>
</SCIMAGOLIST>
```

Sendo que 1414753X é o ISSN_PID e 5600155441 é o ID no SCIMAGO.

```

**Comment by robertatakenaka** [comment]
Resolvido para Brasil (#669):
http://www.scielo.br/scielo.php?script=sci_serial&pid=0100-6045&lng=pt&nrm=iso
http://www.scielo.br/scielo.php?script=sci_serial&pid=2446-4740&lng=pt&nrm=iso
http://www.scielo.br/scielo.php?script=sci_serial&pid=1984-6398&lng=pt&nrm=iso
http://www.scielo.br/scielo.php?script=sci_serial&pid=2238-3875&lng=pt&nrm=iso
