### ISSUE TITLE
[homolog.xml] Caixa de errata não aparece para mais de um artigo

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#675]
O arquivo errata corrige 3 artigos porém só cria uma única caixa no homolog.xml [http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0101-28002018005041101&lng=en&nrm=iso&tlng=en].

Relatório do XC: [http://homolog.xml.scielo.br/reports/jbn/2018nahead/xc_2018-11-09_120956.html]

XML anexado.
[2175-8239-jbn-errata-03.txt](https://github.com/scieloorg/Web/files/2566610/2175-8239-jbn-errata-03.txt)

**Comment by robertatakenaka** [comment]
@alexxpsilva : só vi 1 
```xml
<related-article id="RA1" related-article-type="corrected-article" ext-link-type="doi"
				xlink:href="10.1590/2175-8239-JBN-2018-00030003"/>
```
Teria que ter 1 para cada artigo que é corrigido

**Comment by alexxpsilva** [comment]
@robertatakenaka era isso mesmo, deu certo.

Vou fechar o ticket.
