### ISSUE TITLE
Entidade HTML na resposta do protocolo OAI-PMH

### ISSUE THREAD

**Issue by gustavofonseca** [scieloorg/Web#685]
O erro foi reportado por Mike Lichtenberg, do BHL. 

O conjunto de dados retornados pela interface OAI-PMH apresenta a entidade HTML `<dc:creator>D&#8217;Ávila,V. A.</dc:creator>`, conforme exemplo:

<img width="1912" alt="Screen Shot 2019-06-13 at 11 46 36" src="https://user-images.githubusercontent.com/161335/59442625-170b7000-8dea-11e9-8540-4b5a8f2e18fc.png">

URL que apresenta o problema: http://www.scielo.br/oai/scielo-oai.php?verb=GetRecord&identifier=oai:scielo:S1519-69842016000300796&metadataPrefix=oai_dc

**Comment by joffilyfe** [comment]
### Resultado da exploração inicial

- Acessando a base original e procurando pelo PID do artigo foi possível observar que o dado está escrito desta maneira `D&#8217;?vila` [1];
- Observando a XSLT a criação da tag `dc:creator` é possível perceber que  o valor é encapsulado dentro de uma `<![CDATA[]]>`;
- Por estar dentro de uma tag `CDATA` o valor é interpretado do modo que é entregue ao browser/engine;

### Imagens

[1] - Busca pelo artigo em questão:

<img width="1073" alt="Screen Shot 2019-06-25 at 14 30 21" src="https://user-images.githubusercontent.com/4604104/60120331-f54da980-9756-11e9-8d49-858293252502.png">

**Comment by gustavofonseca** [comment]
Eu imagino que esse caso é mais comum do que aparenta, digo, a ocorrência de entidades html na base de dados ISIS. Você já tem em mente alguma abordagem para solucionar?

**Comment by joffilyfe** [comment]
> Eu imagino que esse caso é mais comum do que aparenta, digo, a ocorrência de entidades html na base de dados ISIS. Você já tem em mente alguma abordagem para solucionar?

Depois de alguns séculos eu tenho uma proposta de solução para o problema, segue a url com um gist https://gist.github.com/joffilyfe/bc6daae8e7c5c40e496d1c2331307b41.

Basicamente transformamos todas as entidades html logo após a XSLT ser gerada.

**Comment by gustavofonseca** [comment]
A abordagem me parece boa. Deixei um comentário no gist.

**Comment by jamilatta** [comment]
@joffilyfe 

Nessa abordagem vejo que resolvemos o problema para o **OAI-PMH**, mas o problema permanece na base de dados, o que talvez seja um problema para os aplicativos que irão fazer uso dos dados da base de dados **ISIS**. 

Como a atividade é para resolver um problema do **OAI-PMH** especificamente, acho a solução satisfatória, porém, recomendo abrimos um tíquete para uma solução que seja na camada da base de dados **ISIS**.

**Comment by joffilyfe** [comment]
> @joffilyfe 
> Como a atividade é para resolver um problema do **OAI-PMH** especificamente, acho a solução satisfatória, porém, recomendo abrimos um tíquete para uma solução que seja na camada da base de dados **ISIS**.

Aparentemente isso não é possível @jamilatta , segundo a @robertatakenaka a base ISIS não suporta o `UTF-8` então estes caracteres precisam ser traduzidos para as suas representações HTML.

Eu acredito em uma solução a posteriori onde nós teremos esses dados no XML (migrado) e na base do Kernel em `UTF-8`.

**Comment by jamilatta** [comment]
@joffilyfe 

OK!

**Comment by joffilyfe** [comment]
Resolução em produção.
