### ISSUE TITLE
[homolog - QA] <history> em <front-stub> não aparece

### ISSUE THREAD

**Issue by marinachagas** [scieloorg/Web#691]
Temos um caso onde as datas de publicação online dos PDFs em português são diferentes das em inglês. 
  

Quando é inserido ```<history>``` em ```<front-stub>``` as datas da tradução somem conforme a imagem abaixo. Entretanto na versão original são mantidas.

![image](https://user-images.githubusercontent.com/53793690/62563907-42df2b00-b85a-11e9-9a33-64a9d9f5835c.png)

Envio XML anexo para análise, e o link do artigo no site de Homologação QA.

[0034-7094-rba-69-03-0227.txt](https://github.com/scieloorg/Web/files/3473545/0034-7094-rba-69-03-0227.txt)

Link de homologação: [http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S0034-70942019000300227&lng=en&nrm=iso&tlng=pt](url)

**Comment by marinachagas** [comment]
Em teste realizado hoje com o Joffily, as informações apareceram corretamente.
O problema reportado não foi exibido.

**Comment by robertatakenaka** [comment]
Da mesma forma que está "traduzido" received e accepted, deveria ser apresentado o rótulo para "publicado".
