### ISSUE TITLE
Ausência de resumos na página do artigo

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/Web#698]
### Descrição do problema
Apresenta ausência de resumos em documentos que foram representados por XML, com sub-article e há mais versões de resumos que versões de texto completo.

### Passos para reproduzir o problema

Texto em português apresenta resumo em português
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1414-753X2019000100301&lng=en&nrm=iso&tlng=pt 

Texto em inglês apresenta resumo em inglês e espanhol
http://www.scielo.br/scielo.php?script=sci_arttext&pid=S1414-753X2019000100301&lng=en&nrm=iso&tlng=en&ORIGINALLANG=en

PDF em inglês (resumo em inglês, português e espanhol):
- http://www.scielo.br/pdf/asoc/v22/1809-4422-asoc-22-e00121.pdf
PDF em português (resumo em inglês, português e espanhol):
- http://www.scielo.br/pdf/asoc/v22/pt_1809-4422-asoc-22-e00121.pdf

### Comportamento esperado
Todos os resumos devem ser apresentados no texto completo, independentemente do idioma do texto.

### Screenshots ou vídeos
<img width="545" alt="Captura de Tela 2019-11-12 às 10 38 17" src="https://user-images.githubusercontent.com/505143/68676323-912a5700-0538-11ea-8753-bcf1126de4fa.png">
<img width="545" alt="Captura de Tela 2019-11-12 às 10 38 01" src="https://user-images.githubusercontent.com/505143/68676331-95567480-0538-11ea-8252-cf73c5db5071.png">

### Anexos
[fwdscielobrasilmultilingualismolimistadopornsme.zip](https://github.com/scieloorg/Web/files/3833003/fwdscielobrasilmultilingualismolimistadopornsme.zip)

Segue a especificação:
https://scielo.readthedocs.io/projects/scielo-publishing-schema/pt_BR/latest/tagset/elemento-trans-abstract.html

### Ambiente utilizado
n/a

**Comment by gustavofonseca** [comment]
> ### Comportamento esperado
> 
> Todos os resumos devem ser apresentados no texto completo, independentemente do idioma do texto.

Você quer dizer que deverá haver uma _herança circular_ entre o artigo principal e seus sub-artigos? Isto é: o artigo principal deve herdar os resumos definidos nos sub-artigos e cada sub-artigo deve herdar os resumos do artigo principal e dos demais sub-artigos?

**Comment by robertatakenaka** [comment]
@gustavofonseca acho que é incorreto pensar em herança quando o sub-article é tradução.

**Comment by gustavofonseca** [comment]
Qual seria então a melhor forma de pensar a relação entre as partes no contexto do documento XML?

**Comment by robertatakenaka** [comment]
@gustavofonseca não sei. mas tampouco é como está no PDF.
Olha como estão os PDF. Esse modelo de apresentação não é recente já vi casos desde 1997.
Eles colocam todos os resumos no final independentemente do idioma do texto.

**Comment by robertatakenaka** [comment]
@gustavofonseca acho que as questões seriam:

-  o modo como está representado no XML deveria afetar o modo de apresentação?
   - se sim, todos os resumos deveriam estar dentro de article-meta, porque deste modo poderíamos considerar "herdáveis" para todos os demais idiomas... mas também se o "editor" não quiser resumos "herdáveis", cada resumo deveria estar dentro do sub-article correspondente.
   ou seja, a forma de mostrar estaria diretamente associada à estrutura do XML.

- o modo de apresentar é de acordo com o interesse do SciELO de promover internacionalização/multilinguismo?
   - se sim, independentemente da forma como está representado no XML deveriam ser apresentados todos os resumos/palavras-chaves. 

pela mensagem que recebemos me parece que é o segundo caso.

**Comment by gustavofonseca** [comment]
> * o modo como está representado no XML deveria afetar o modo de apresentação?

Sim, definitivamente. _Representação_ e a _interpretação_ estão intimamente ligadas. 

O ponto é que eu não vejo os 2 tópicos que vc colocou como mutuamente exclusivos. Acho que é possível pensarmos em representações e interpretações interessantes ao SciELO e que sejam bem definidas.

**Comment by lpanebr** [comment]
Esta discussão é interessante. Pensar na solução técnica para todo o backlog e para o futuro parece difícil mesmo.

Uma possível solução para futuro não seria exigir que tanto o `article` quantos os seus `sub-article`s contenham todas as versões disponíveis do `abstract`? Isso implica em mudar SPS para forçar que ocorra essa redundância de abstracts. Essa redundância tem **um lado negativo** que é a possibilidade de erro por parte dos prestadores (total de abstracts diferente ou abstracts diferentes para o mesmo idioma). **Criar as checagens nos vários apps scielo seria trabalhoso.** Por outro lado, **um ponto positivo** é que tendo todos os abstracts representados, não seria necessário criar lógicas para lidar com heranças e a interpretação ficaria menos complexa.
