### ISSUE TITLE
XML - palavra chave em itálico

### ISSUE THREAD

**Issue by alexxpsilva** [scieloorg/Web#724]
O site não permite palavras chaves em itálico

1678-9199-jvatitd-26-e20200041 -  Leiurus

1678-9199-jvatitd-26-e20190041 -  Micrurus lemniscatus

1678-9199-jvatitd-26-e20190047 - Naja naja

1678-9199-jvatitd-26-e20190078 -  Argenteohyla siemersi

1678-9199-jvatitd-26-e20190103 - Bothrops brazili

1678-9199-jvatitd-26-e20190095 -  Conus bandanus

Links em homolog de artigos com esse problema:

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100202&lng=en&nrm=iso&tlng=en (esse é o caso principal)
 
http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100301&lng=en&nrm=iso&tlng=en 

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100304&lng=en&nrm=iso&tlng=en

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100306&lng=en&nrm=iso&tlng=en 

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100308&lng=en&nrm=iso&tlng=en 

http://homolog.xml.scielo.br/scielo.php?script=sci_arttext&pid=S1678-91992020000100311&lng=en&nrm=iso&tlng=en 

Envio os xmls's destes arquivos.

[xmls-keywords-italic.zip](https://github.com/scieloorg/Web/files/4795103/xmls-keywords-italic.zip)

**Comment by robertatakenaka** [comment]
@scieloorg/scielo-brazil-developers Problema no bloco:

https://github.com/scieloorg/Web/blob/01533aaded17a2ff16bc27dfaa83fe2709a2f7e7/htdocs/xsl/pmc/v3.0/scielo-fulltext.xsl#L370

**Comment by joffilyfe** [comment]
@alexxpsilva o sistema em produção foi atualizado, você poderia por favor verificar se a atualização corrige o problema?
