### ISSUE TITLE
Artigo HTML BR aparece duas vezes na mesma página

### ISSUE THREAD

**Issue by JoyceRaphaela** [scieloorg/Web#730]
O seguinte artigo HTML BR está aparecendo duas vezes na mesma página no site: https://www.scielo.br/scielo.php?script=sci_arttext&pid=S0100-55022012000100020&lng=en&nrm=iso&tlng=pt
Tentei gerar novamente o artigo convertendo pelo Converter BR e gerando com o GeraPadrao BR - HTML e acabei verificando que mais dois artigos do mesmo fascículo aparecem na mesma página dele no interno-scielo: http://interno-scielo/scielo.php?script=sci_arttext&pid=S0100-55022012000100020&lng=pt&nrm=iso&tlng=pt

Caminho para a pasta do fascículo:
V:\SciELO\serial\rbem\v36n1
Nomeação dos arquivos contidos na pasta que são referentes ao artigo com o problema relatado:
a20v36n1

**Comment by robertatakenaka** [comment]
Ações de correção:
Caso 1
Verifique o documento html referente ao artigo em questão, ou seja, o documento que está na pasta "body". Ele está duplicado?

    Solução: corrigir o documento que está no body

Caso 2 (mais provável)
Está duplicado na base de dados, provavelmente porque durante a conversão o programa foi interrompido e a base ficou danificada.
Solução: Renomeie a pasta "base" e execute o Converter para todos os documentos e repita todos os passos até a publicação
